/* ============================================================================
 *  ota_page.h  --  Embedded HTML for the PTP Slave OTA firmware update page
 *
 *  Served at GET /ota by the web server. The page POSTs the firmware .bin
 *  to /api/ota and polls /api/ota/info for partition status. See
 *  ota_handler.h for the C-side endpoints.
 *
 *  Project: https://github.com/Montecri/GNSSTimeServer
 *
 *  NOTE: Auto-generated from ota.html. Do not edit by hand -- re-run
 *        build_ota_page.py whenever ota.html changes, then rebuild & flash.
 * ============================================================================ */

#ifndef OTA_PAGE_H
#define OTA_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

static const char OTA_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<link rel=\"icon\" type=\"image/svg+xml\" href=\"data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2064%2064'%3E%3Cdefs%3E%3ClinearGradient%20id='g'%20x1='0'%20y1='0'%20x2='1'%20y2='1'%3E%3Cstop%20offset='0'%20stop-color='%23ffb86c'/%3E%3Cstop%20offset='1'%20stop-color='%23ff5577'/%3E%3C/linearGradient%3E%3C/defs%3E%3Ccircle%20cx='32'%20cy='32'%20r='28'%20fill='%230b1018'%20stroke='url(%23g)'%20stroke-width='4'/%3E%3Cpath%20d='M%2032%2050%20L%2032%2022%20M%2022%2032%20L%2032%2022%20L%2042%2032'%20stroke='%23ffb86c'%20stroke-width='5'%20stroke-linecap='round'%20stroke-linejoin='round'%20fill='none'/%3E%3C/svg%3E\">\n"
    "<title>OTA Update &mdash; ESP32-P4 PTP Slave</title>\n"
    "<style>\n"
    "  :root {\n"
    "    --bg-0:#0b1018; --bg-1:#121a26; --bg-2:#1a2536; --bg-3:#233047;\n"
    "    --line:#2a3a55; --line-soft:#1f2c42;\n"
    "    --text:#e6edf7; --text-dim:#8fa1bf; --text-mute:#5a6c8a;\n"
    "    --accent:#7aa2f7; --accent-2:#bd93f9;\n"
    "    --ok:#50fa7b; --warn:#ffb86c; --err:#ff5577;\n"
    "    --info:#8be9fd; --purple:#bd93f9; --gold:#f1c40f;\n"
    "    --grid-glow:rgba(122,162,247,0.08);\n"
    "    --mono:ui-monospace,\"SF Mono\",\"JetBrains Mono\",\"Cascadia Code\",Consolas,\"Courier New\",monospace;\n"
    "    --sans:-apple-system,BlinkMacSystemFont,\"Segoe UI\",system-ui,sans-serif;\n"
    "    --emoji:\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Noto Color Emoji\",\"Segoe UI Symbol\",sans-serif;\n"
    "  }\n"
    "  * { box-sizing:border-box; }\n"
    "  html,body { margin:0; padding:0; background:var(--bg-0); color:var(--text); font-family:var(--sans); -webkit-font-smoothing:antialiased; min-height:100vh; }\n"
    "  body {\n"
    "    background:\n"
    "      radial-gradient(circle at 15% 0%, rgba(122,162,247,0.06) 0%, transparent 40%),\n"
    "      radial-gradient(circle at 85% 100%, rgba(189,147,249,0.05) 0%, transparent 40%),\n"
    "      linear-gradient(180deg,var(--bg-0) 0%,#060a12 100%);\n"
    "    background-attachment:fixed;\n"
    "  }\n"
    "  body::before {\n"
    "    content:\"\"; position:fixed; inset:0;\n"
    "    background-image:\n"
    "      linear-gradient(var(--grid-glow) 1px,transparent 1px),\n"
    "      linear-gradient(90deg,var(--grid-glow) 1px,transparent 1px);\n"
    "    background-size:48px 48px; pointer-events:none; z-index:0; opacity:0.4;\n"
    "  }\n"
    "  .container { position:relative; z-index:1; max-width:760px; margin:0 auto; padding:28px 24px 48px; }\n"
    "\n"
    "  header { display:flex; align-items:center; justify-content:space-between; gap:16px;\n"
    "           padding-bottom:20px; border-bottom:1px solid var(--line-soft); margin-bottom:24px; flex-wrap:wrap; }\n"
    "  .brand { display:flex; align-items:center; gap:14px; }\n"
    "  .brand .mark { width:44px; height:44px; border-radius:10px;\n"
    "                 background:linear-gradient(135deg,var(--warn) 0%,var(--err) 100%);\n"
    "                 display:flex; align-items:center; justify-content:center;\n"
    "                 font-size:22px;\n"
    "                 box-shadow:0 0 24px rgba(255,184,108,0.3); }\n"
    "  .brand h1 { margin:0; font-size:20px; font-weight:600; letter-spacing:0.2px; }\n"
    "  .brand .sub { margin:2px 0 0; font-family:var(--mono); font-size:11px; color:var(--text-dim); letter-spacing:0.5px; }\n"
    "\n"
    "  .back { font-family:var(--mono); font-size:12px; color:var(--text-dim); text-decoration:none;\n"
    "          padding:8px 14px; border-radius:999px; border:1px solid var(--line-soft); transition:all 0.2s ease; }\n"
    "  .back:hover { color:var(--accent); border-color:var(--accent); }\n"
    "\n"
    "  .card { background:linear-gradient(180deg,var(--bg-1) 0%,var(--bg-2) 100%);\n"
    "          border:1px solid var(--line-soft); border-radius:14px; padding:24px;\n"
    "          position:relative; overflow:hidden; margin-bottom:18px; }\n"
    "  .card::before { content:\"\"; position:absolute; top:0; left:0; right:0; height:1px;\n"
    "                  background:linear-gradient(90deg,transparent,var(--line),transparent); }\n"
    "  .card-header { display:flex; align-items:center; justify-content:space-between;\n"
    "                 margin-bottom:18px; padding-bottom:12px; border-bottom:1px dashed var(--line-soft); }\n"
    "  .card-header h2 { margin:0; font-size:11px; font-weight:700; letter-spacing:2px;\n"
    "                    text-transform:uppercase; color:var(--text-dim); }\n"
    "  .card-header .badge { font-family:var(--mono); font-size:10px; color:var(--text-mute); letter-spacing:0.5px; }\n"
    "\n"
    "  /* Partition info rows */\n"
    "  .rows { display:flex; flex-direction:column; gap:2px; }\n"
    "  .row { display:grid; grid-template-columns:28px 1fr auto; align-items:center; gap:12px;\n"
    "         padding:9px 4px; }\n"
    "  .row + .row { border-top:1px solid var(--line-soft); }\n"
    "  .row .icon { font-family:var(--emoji); font-size:18px; line-height:1;\n"
    "               text-align:center; width:28px; display:inline-flex;\n"
    "               align-items:center; justify-content:center; }\n"
    "  .row .label { font-size:13px; color:var(--text); font-weight:500; }\n"
    "  .row .label .hint { display:block; font-family:var(--mono); font-size:10px;\n"
    "                      color:var(--text-mute); font-weight:400; margin-top:2px; }\n"
    "  .row .value { font-family:var(--mono); font-size:12.5px; color:var(--text);\n"
    "                text-align:right; font-variant-numeric:tabular-nums; }\n"
    "  .row .value.dim   { color:var(--text-dim); }\n"
    "  .row .value.ok    { color:var(--ok); }\n"
    "  .row .value.warn  { color:var(--warn); }\n"
    "  .row .value.accent{ color:var(--accent); }\n"
    "\n"
    "  /* Auth inputs (Basic Auth for POST /api/ota) */\n"
    "  .auth-row {\n"
    "    display:flex;\n"
    "    gap:10px;\n"
    "    margin-bottom:18px;\n"
    "    flex-wrap:wrap;\n"
    "  }\n"
    "  .auth-row label {\n"
    "    flex:1;\n"
    "    min-width:140px;\n"
    "    display:flex;\n"
    "    flex-direction:column;\n"
    "    gap:6px;\n"
    "  }\n"
    "  .auth-row .auth-label {\n"
    "    font-family:var(--mono);\n"
    "    font-size:10px;\n"
    "    color:var(--text-dim);\n"
    "    letter-spacing:1.5px;\n"
    "    text-transform:uppercase;\n"
    "  }\n"
    "  .auth-row input {\n"
    "    padding:10px 12px;\n"
    "    background:var(--bg-2);\n"
    "    color:var(--text);\n"
    "    border:1px solid var(--line);\n"
    "    border-radius:8px;\n"
    "    font-family:var(--mono);\n"
    "    font-size:13px;\n"
    "    transition:all 0.2s ease;\n"
    "  }\n"
    "  .auth-row input:focus {\n"
    "    outline:none;\n"
    "    border-color:var(--accent);\n"
    "    box-shadow:0 0 0 3px rgba(122,162,247,0.1);\n"
    "  }\n"
    "\n"
    "  /* File picker */\n"
    "  .drop-zone {\n"
    "    display:block;\n"
    "    border:2px dashed var(--line);\n"
    "    border-radius:12px;\n"
    "    padding:36px 24px;\n"
    "    text-align:center;\n"
    "    transition:all 0.2s ease;\n"
    "    cursor:pointer;\n"
    "    background:rgba(255,255,255,0.01);\n"
    "  }\n"
    "  .drop-zone:hover, .drop-zone.dragover {\n"
    "    border-color:var(--accent);\n"
    "    background:rgba(122,162,247,0.04);\n"
    "  }\n"
    "  .drop-zone .icon-big {\n"
    "    font-family:var(--emoji);\n"
    "    font-size:42px;\n"
    "    display:block;\n"
    "    margin-bottom:12px;\n"
    "  }\n"
    "  .drop-zone .primary {\n"
    "    font-size:15px;\n"
    "    font-weight:600;\n"
    "    color:var(--text);\n"
    "    margin-bottom:6px;\n"
    "  }\n"
    "  .drop-zone .secondary {\n"
    "    font-family:var(--mono);\n"
    "    font-size:11px;\n"
    "    color:var(--text-mute);\n"
    "    letter-spacing:0.3px;\n"
    "  }\n"
    "  .drop-zone.has-file {\n"
    "    border-color:var(--accent);\n"
    "    border-style:solid;\n"
    "    background:rgba(122,162,247,0.06);\n"
    "  }\n"
    "  .drop-zone.has-file .icon-big { content:none; }\n"
    "  .file-info {\n"
    "    font-family:var(--mono);\n"
    "    color:var(--accent);\n"
    "    font-size:13px;\n"
    "    margin-top:8px;\n"
    "  }\n"
    "  .file-info .name { color:var(--text); }\n"
    "  .file-info .size { color:var(--text-dim); font-size:11px; }\n"
    "\n"
    "  input[type=file] { display:none; }\n"
    "\n"
    "  /* Buttons */\n"
    "  .btn-row { display:flex; gap:12px; margin-top:18px; }\n"
    "  .btn {\n"
    "    flex:1;\n"
    "    padding:12px 18px;\n"
    "    border-radius:10px;\n"
    "    border:1px solid var(--line);\n"
    "    background:var(--bg-3);\n"
    "    color:var(--text);\n"
    "    font-family:var(--sans);\n"
    "    font-size:14px;\n"
    "    font-weight:600;\n"
    "    letter-spacing:0.3px;\n"
    "    cursor:pointer;\n"
    "    transition:all 0.2s ease;\n"
    "    display:inline-flex; align-items:center; justify-content:center; gap:8px;\n"
    "  }\n"
    "  .btn:hover:not(:disabled) { transform:translateY(-1px); border-color:var(--accent); }\n"
    "  .btn:disabled { opacity:0.4; cursor:not-allowed; }\n"
    "  .btn.primary {\n"
    "    background:linear-gradient(135deg,var(--accent) 0%,var(--accent-2) 100%);\n"
    "    color:var(--bg-0);\n"
    "    border-color:transparent;\n"
    "    box-shadow:0 4px 16px rgba(122,162,247,0.2);\n"
    "  }\n"
    "  .btn.primary:hover:not(:disabled) {\n"
    "    box-shadow:0 6px 20px rgba(122,162,247,0.35);\n"
    "  }\n"
    "  .btn.danger {\n"
    "    background:rgba(255,85,119,0.08);\n"
    "    border-color:rgba(255,85,119,0.3);\n"
    "    color:var(--err);\n"
    "  }\n"
    "  .btn.danger:hover:not(:disabled) { background:rgba(255,85,119,0.15); }\n"
    "\n"
    "  /* Progress */\n"
    "  .progress-wrap {\n"
    "    display:none;\n"
    "    margin-top:20px;\n"
    "    padding:18px;\n"
    "    background:rgba(0,0,0,0.2);\n"
    "    border-radius:10px;\n"
    "    border:1px solid var(--line-soft);\n"
    "  }\n"
    "  .progress-wrap.visible { display:block; }\n"
    "  .progress-label {\n"
    "    display:flex; justify-content:space-between; align-items:center;\n"
    "    font-family:var(--mono); font-size:12px; margin-bottom:10px;\n"
    "  }\n"
    "  .progress-label .stage { color:var(--accent); letter-spacing:1px; }\n"
    "  .progress-label .pct { color:var(--text); font-weight:700; }\n"
    "  .progress-bar {\n"
    "    height:8px; background:var(--bg-3); border-radius:99px; overflow:hidden; position:relative;\n"
    "  }\n"
    "  .progress-bar > i {\n"
    "    display:block; height:100%; width:0%;\n"
    "    background:linear-gradient(90deg,var(--accent),var(--accent-2));\n"
    "    border-radius:99px;\n"
    "    transition:width 0.2s ease;\n"
    "  }\n"
    "  .progress-meta {\n"
    "    margin-top:10px;\n"
    "    display:flex; justify-content:space-between;\n"
    "    font-family:var(--mono); font-size:10px; color:var(--text-mute);\n"
    "    letter-spacing:0.5px;\n"
    "  }\n"
    "\n"
    "  /* Status callouts */\n"
    "  .alert {\n"
    "    margin-top:16px;\n"
    "    padding:12px 16px;\n"
    "    border-radius:8px;\n"
    "    font-size:13px;\n"
    "    line-height:1.5;\n"
    "    display:flex; align-items:flex-start; gap:10px;\n"
    "  }\n"
    "  .alert .icon { font-family:var(--emoji); font-size:18px; flex-shrink:0; }\n"
    "  .alert.info { background:rgba(139,233,253,0.06); border:1px solid rgba(139,233,253,0.2); color:var(--info); }\n"
    "  .alert.warn { background:rgba(255,184,108,0.06); border:1px solid rgba(255,184,108,0.2); color:var(--warn); }\n"
    "  .alert.err  { background:rgba(255,85,119,0.06); border:1px solid rgba(255,85,119,0.2); color:var(--err); }\n"
    "  .alert.ok   { background:rgba(80,250,123,0.06); border:1px solid rgba(80,250,123,0.2); color:var(--ok); }\n"
    "  .alert .body { flex:1; }\n"
    "  .alert .body strong { display:block; margin-bottom:2px; font-weight:700; }\n"
    "\n"
    "  /* Footer */\n"
    "  footer { margin-top:32px; padding-top:16px; border-top:1px solid var(--line-soft);\n"
    "           text-align:center; font-family:var(--mono); font-size:10.5px;\n"
    "           color:var(--text-mute); letter-spacing:1px; }\n"
    "  footer a { color:var(--accent); text-decoration:none; border-bottom:1px dashed transparent; }\n"
    "  footer a:hover { border-bottom-color:var(--accent); }\n"
    "  footer .sep { margin:0 8px; color:var(--text-mute); opacity:0.5; }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"container\">\n"
    "\n"
    "  <header>\n"
    "    <div class=\"brand\">\n"
    "      <div class=\"mark\">&#x1F4E1;</div>\n"
    "      <div>\n"
    "        <h1>Firmware Update (OTA)</h1>\n"
    "        <div class=\"sub\">ESP32-P4 PTP Slave &middot; over-the-air image upload</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <a class=\"back\" href=\"/\">&larr; Status page</a>\n"
    "  </header>\n"
    "\n"
    "  <!-- Current firmware -->\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-header\">\n"
    "      <h2>Current Firmware</h2>\n"
    "      <span class=\"badge\" id=\"b_ota\">checking&hellip;</span>\n"
    "    </div>\n"
    "    <div class=\"rows\">\n"
    "      <div class=\"row\">\n"
    "        <span class=\"icon\">&#x1F4E6;</span>\n"
    "        <span class=\"label\">Project<span class=\"hint\" id=\"i_compile\">&mdash;</span></span>\n"
    "        <span class=\"value\" id=\"i_project\">&mdash;</span>\n"
    "      </div>\n"
    "      <div class=\"row\">\n"
    "        <span class=\"icon\">&#x1F3F7;&#xFE0F;</span>\n"
    "        <span class=\"label\">Version</span>\n"
    "        <span class=\"value accent\" id=\"i_version\">&mdash;</span>\n"
    "      </div>\n"
    "      <div class=\"row\">\n"
    "        <span class=\"icon\">&#x1F4BE;</span>\n"
    "        <span class=\"label\">Running partition<span class=\"hint\" id=\"i_run_addr\">&mdash;</span></span>\n"
    "        <span class=\"value\" id=\"i_run_label\">&mdash;</span>\n"
    "      </div>\n"
    "      <div class=\"row\">\n"
    "        <span class=\"icon\">&#x1F501;</span>\n"
    "        <span class=\"label\">Next update slot<span class=\"hint\" id=\"i_next_addr\">&mdash;</span></span>\n"
    "        <span class=\"value\" id=\"i_next_label\">&mdash;</span>\n"
    "      </div>\n"
    "      <div class=\"row\">\n"
    "        <span class=\"icon\">&#x1F4D0;</span>\n"
    "        <span class=\"label\">Slot capacity</span>\n"
    "        <span class=\"value dim\" id=\"i_next_size\">&mdash;</span>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Upload card -->\n"
    "  <div class=\"card\" id=\"uploadCard\">\n"
    "    <div class=\"card-header\">\n"
    "      <h2>Upload New Image</h2>\n"
    "      <span class=\"badge\">.bin file from <code>idf.py build</code></span>\n"
    "    </div>\n"
    "\n"
    "    <!-- Basic Auth credentials. These are sent as Authorization: Basic <base64>\n"
    "         on the upload POST. Must match the user:password whose Base64 is\n"
    "         compiled into OTA_BASIC_AUTH_B64 (ota_credentials.h on the device). -->\n"
    "    <div class=\"auth-row\">\n"
    "      <label>\n"
    "        <span class=\"auth-label\">Username</span>\n"
    "        <input id=\"otaUser\" type=\"text\" autocomplete=\"username\" value=\"admin\">\n"
    "      </label>\n"
    "      <label>\n"
    "        <span class=\"auth-label\">Password</span>\n"
    "        <input id=\"otaPass\" type=\"password\" autocomplete=\"current-password\" placeholder=\"set in ota_credentials.h\">\n"
    "      </label>\n"
    "    </div>\n"
    "\n"
    "    <label class=\"drop-zone\" id=\"dropZone\" for=\"fileInput\">\n"
    "      <span class=\"icon-big\">&#x1F4E5;</span>\n"
    "      <div class=\"primary\" id=\"dropPrimary\">Click to choose firmware or drop here</div>\n"
    "      <div class=\"secondary\" id=\"dropSecondary\">expects: build/PTP_Slave.bin (typically 600 KB &ndash; 3 MB)</div>\n"
    "      <div class=\"file-info\" id=\"fileInfo\" style=\"display:none;\">\n"
    "        <div class=\"name\" id=\"fileName\"></div>\n"
    "        <div class=\"size\" id=\"fileSize\"></div>\n"
    "      </div>\n"
    "      <input type=\"file\" id=\"fileInput\" accept=\".bin,application/octet-stream\">\n"
    "    </label>\n"
    "\n"
    "    <div class=\"btn-row\">\n"
    "      <button class=\"btn danger\" id=\"clearBtn\" disabled>Clear</button>\n"
    "      <button class=\"btn primary\" id=\"uploadBtn\" disabled>\n"
    "        <span>&#x1F680;</span><span>Upload &amp; Flash</span>\n"
    "      </button>\n"
    "    </div>\n"
    "\n"
    "    <div class=\"progress-wrap\" id=\"progressWrap\">\n"
    "      <div class=\"progress-label\">\n"
    "        <span class=\"stage\" id=\"progStage\">UPLOADING</span>\n"
    "        <span class=\"pct\" id=\"progPct\">0%</span>\n"
    "      </div>\n"
    "      <div class=\"progress-bar\"><i id=\"progBar\"></i></div>\n"
    "      <div class=\"progress-meta\">\n"
    "        <span id=\"progBytes\">0 / 0 B</span>\n"
    "        <span id=\"progSpeed\">&mdash;</span>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"alertSlot\"></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Warning -->\n"
    "  <div class=\"alert warn\">\n"
    "    <span class=\"icon\">&#x26A0;&#xFE0F;</span>\n"
    "    <div class=\"body\">\n"
    "      <strong>Heads up</strong>\n"
    "      Uploading a new firmware image will reboot the slave once flashing completes.\n"
    "      The PTP slave will briefly drop its lock during the ~3 s reboot window and\n"
    "      then re-acquire from the grandmaster automatically. Make sure the .bin file\n"
    "      targets <code>esp32p4</code> &mdash; a wrong-target image will be rejected at\n"
    "      validation.\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <footer>\n"
    "    <a href=\"https://github.com/Montecri/GNSSTimeServer\" target=\"_blank\" rel=\"noopener\">github.com/Montecri/GNSSTimeServer</a>\n"
    "  </footer>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "\"use strict\";\n"
    "\n"
    "const $ = (id) => document.getElementById(id);\n"
    "\n"
    "let selectedFile = null;\n"
    "let uploadXHR    = null;\n"
    "\n"
    "/* ─── Load partition info on page load ─── */\n"
    "async function loadInfo() {\n"
    "  try {\n"
    "    const r = await fetch(\"/api/ota/info\", { cache: \"no-store\" });\n"
    "    if (!r.ok) throw new Error(\"HTTP \" + r.status);\n"
    "    const d = await r.json();\n"
    "\n"
    "    $(\"i_project\").textContent = d.project || \"\\u2014\";\n"
    "    $(\"i_compile\").textContent = d.compile_time || \"\";\n"
    "    $(\"i_version\").textContent = d.app_version || \"\\u2014\";\n"
    "\n"
    "    if (d.running) {\n"
    "      $(\"i_run_label\").textContent = d.running.label;\n"
    "      $(\"i_run_addr\").textContent  = \"@ \" + d.running.address;\n"
    "    }\n"
    "\n"
    "    if (d.next_update) {\n"
    "      $(\"i_next_label\").textContent = d.next_update.label;\n"
    "      $(\"i_next_addr\").textContent  = \"@ \" + d.next_update.address;\n"
    "      $(\"i_next_size\").textContent  = (d.next_update.size / 1024 / 1024).toFixed(1) + \" MB (\"\n"
    "                                    + d.next_update.size.toLocaleString() + \" B)\";\n"
    "    } else {\n"
    "      $(\"i_next_label\").textContent = \"(none)\";\n"
    "    }\n"
    "\n"
    "    if (!d.ota_supported) {\n"
    "      $(\"b_ota\").textContent = \"OTA UNAVAILABLE\";\n"
    "      $(\"b_ota\").style.color = \"var(--err)\";\n"
    "      showAlert(\"err\", \"OTA partitions missing\",\n"
    "        \"This firmware was built with a single-slot partition table. \" +\n"
    "        \"Re-flash once over UART using partitions_ota.csv (see ota_handler.h). \" +\n"
    "        \"Subsequent updates can then use this page.\");\n"
    "      $(\"uploadBtn\").disabled = true;\n"
    "      $(\"fileInput\").disabled = true;\n"
    "    } else if (d.ota_in_progress) {\n"
    "      $(\"b_ota\").textContent = \"BUSY\";\n"
    "      $(\"b_ota\").style.color = \"var(--warn)\";\n"
    "      showAlert(\"warn\", \"OTA already in progress\",\n"
    "        \"Another upload is currently running. Wait for it to finish or reboot.\");\n"
    "    } else {\n"
    "      $(\"b_ota\").textContent = \"READY\";\n"
    "      $(\"b_ota\").style.color = \"var(--ok)\";\n"
    "    }\n"
    "  } catch (e) {\n"
    "    $(\"b_ota\").textContent = \"OFFLINE\";\n"
    "    $(\"b_ota\").style.color = \"var(--err)\";\n"
    "    showAlert(\"err\", \"Could not query device\", e.message);\n"
    "  }\n"
    "}\n"
    "\n"
    "/* ─── File picker / drag-drop ─── */\n"
    "const dz = $(\"dropZone\");\n"
    "const fi = $(\"fileInput\");\n"
    "\n"
    "function fmtSize(b) {\n"
    "  if (b < 1024) return b + \" B\";\n"
    "  if (b < 1024*1024) return (b/1024).toFixed(1) + \" KB\";\n"
    "  return (b/1024/1024).toFixed(2) + \" MB\";\n"
    "}\n"
    "\n"
    "function setFile(f) {\n"
    "  selectedFile = f;\n"
    "  if (f) {\n"
    "    $(\"dropPrimary\").style.display = \"none\";\n"
    "    $(\"dropSecondary\").style.display = \"none\";\n"
    "    $(\"fileInfo\").style.display = \"block\";\n"
    "    $(\"fileName\").textContent = f.name;\n"
    "    $(\"fileSize\").textContent = fmtSize(f.size);\n"
    "    dz.classList.add(\"has-file\");\n"
    "    $(\"uploadBtn\").disabled = false;\n"
    "    $(\"clearBtn\").disabled  = false;\n"
    "  } else {\n"
    "    $(\"dropPrimary\").style.display = \"\";\n"
    "    $(\"dropSecondary\").style.display = \"\";\n"
    "    $(\"fileInfo\").style.display = \"none\";\n"
    "    dz.classList.remove(\"has-file\");\n"
    "    $(\"uploadBtn\").disabled = true;\n"
    "    $(\"clearBtn\").disabled  = true;\n"
    "    fi.value = \"\";\n"
    "  }\n"
    "}\n"
    "\n"
    "fi.addEventListener(\"change\", (e) => {\n"
    "  const f = e.target.files[0];\n"
    "  if (f) setFile(f);\n"
    "});\n"
    "\n"
    "dz.addEventListener(\"dragover\", (e) => { e.preventDefault(); dz.classList.add(\"dragover\"); });\n"
    "dz.addEventListener(\"dragleave\", () => dz.classList.remove(\"dragover\"));\n"
    "dz.addEventListener(\"drop\", (e) => {\n"
    "  e.preventDefault();\n"
    "  dz.classList.remove(\"dragover\");\n"
    "  if (e.dataTransfer.files.length) setFile(e.dataTransfer.files[0]);\n"
    "});\n"
    "\n"
    "$(\"clearBtn\").addEventListener(\"click\", () => setFile(null));\n"
    "\n"
    "/* ─── Alerts ─── */\n"
    "function showAlert(type, title, body) {\n"
    "  const icons = { info: \"\\u2139\\uFE0F\", warn: \"\\u26A0\\uFE0F\", err: \"\\u274C\", ok: \"\\u2705\" };\n"
    "  $(\"alertSlot\").innerHTML =\n"
    "    '<div class=\"alert ' + type + '\">'\n"
    "    + '<span class=\"icon\">' + (icons[type] || \"\") + '</span>'\n"
    "    + '<div class=\"body\"><strong>' + title + '</strong>' + body + '</div></div>';\n"
    "}\n"
    "\n"
    "function clearAlert() { $(\"alertSlot\").innerHTML = \"\"; }\n"
    "\n"
    "/* ─── Re-enable controls after a failed/aborted upload ─── */\n"
    "function unlockControls() {\n"
    "  $(\"uploadBtn\").disabled = false;\n"
    "  $(\"clearBtn\").disabled  = false;\n"
    "  fi.disabled = false;\n"
    "}\n"
    "\n"
    "/* ─── Upload ─── */\n"
    "$(\"uploadBtn\").addEventListener(\"click\", () => {\n"
    "  if (!selectedFile) return;\n"
    "  clearAlert();\n"
    "  startUpload(selectedFile);\n"
    "});\n"
    "\n"
    "function startUpload(file) {\n"
    "  $(\"uploadBtn\").disabled = true;\n"
    "  $(\"clearBtn\").disabled  = true;\n"
    "  fi.disabled = true;\n"
    "\n"
    "  /* Read credentials FIRST. If the user left them blank we bail before\n"
    "   * disturbing the progress UI — the device requires Basic Auth on\n"
    "   * POST /api/ota and would just return 401 anyway. */\n"
    "  const user = ($(\"otaUser\").value || \"\").trim();\n"
    "  const pass = $(\"otaPass\").value || \"\";\n"
    "  if (!user) {\n"
    "    showAlert(\"err\", \"Username required\",\n"
    "      \"Enter the username that matches the credential compiled into \"\n"
    "      + \"<code>OTA_BASIC_AUTH_B64</code> (see <code>ota_credentials.h</code>).\");\n"
    "    unlockControls();\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  const pw = $(\"progressWrap\");\n"
    "  pw.classList.add(\"visible\");\n"
    "  $(\"progStage\").textContent = \"UPLOADING\";\n"
    "  $(\"progPct\").textContent   = \"0%\";\n"
    "  $(\"progBar\").style.width   = \"0%\";\n"
    "  $(\"progBytes\").textContent = \"0 / \" + fmtSize(file.size);\n"
    "  $(\"progSpeed\").textContent = \"starting\\u2026\";\n"
    "\n"
    "  const xhr = new XMLHttpRequest();\n"
    "  uploadXHR = xhr;\n"
    "\n"
    "  const startMs = Date.now();\n"
    "\n"
    "  xhr.upload.addEventListener(\"progress\", (e) => {\n"
    "    if (!e.lengthComputable) return;\n"
    "    const pct = Math.round(100 * e.loaded / e.total);\n"
    "    $(\"progPct\").textContent = pct + \"%\";\n"
    "    $(\"progBar\").style.width = pct + \"%\";\n"
    "    $(\"progBytes\").textContent = fmtSize(e.loaded) + \" / \" + fmtSize(e.total);\n"
    "    const elapsedS = (Date.now() - startMs) / 1000;\n"
    "    if (elapsedS > 0.5) {\n"
    "      const bps = e.loaded / elapsedS;\n"
    "      $(\"progSpeed\").textContent = fmtSize(bps) + \"/s\";\n"
    "    }\n"
    "  });\n"
    "\n"
    "  xhr.upload.addEventListener(\"load\", () => {\n"
    "    $(\"progStage\").textContent = \"FLASHING\";\n"
    "    $(\"progSpeed\").textContent = \"writing to flash\\u2026\";\n"
    "  });\n"
    "\n"
    "  xhr.addEventListener(\"load\", () => {\n"
    "    if (xhr.status >= 200 && xhr.status < 300) {\n"
    "      $(\"progStage\").textContent = \"DONE\";\n"
    "      $(\"progPct\").textContent = \"100%\";\n"
    "      $(\"progBar\").style.width = \"100%\";\n"
    "      showAlert(\"ok\", \"Upload complete \\u2014 device rebooting\",\n"
    "        \"The slave will reboot into the new image in ~1 second. \"\n"
    "        + \"After reboot, refresh this page to verify the new version.\");\n"
    "      setTimeout(waitForReboot, 3000);\n"
    "    } else if (xhr.status === 401) {\n"
    "      $(\"progStage\").textContent = \"FAILED\";\n"
    "      showAlert(\"err\", \"Authentication rejected (HTTP 401)\",\n"
    "        \"Check the username and password. The device expects the credentials \"\n"
    "        + \"whose Base64 is compiled into <code>OTA_BASIC_AUTH_B64</code> \"\n"
    "        + \"in <code>ota_credentials.h</code>.\");\n"
    "      unlockControls();\n"
    "    } else if (xhr.status === 503) {\n"
    "      $(\"progStage\").textContent = \"FAILED\";\n"
    "      showAlert(\"err\", \"OTA disabled on device (HTTP 503)\",\n"
    "        \"<code>OTA_BASIC_AUTH_B64</code> is still set to the sentinel \"\n"
    "        + \"(<code>REPLACE_ME</code>). Set a real credential, rebuild, and \"\n"
    "        + \"flash once over UART to enable network OTA.\");\n"
    "      unlockControls();\n"
    "    } else if (xhr.status === 409) {\n"
    "      $(\"progStage\").textContent = \"FAILED\";\n"
    "      showAlert(\"warn\", \"OTA already in progress (HTTP 409)\",\n"
    "        \"Another upload is currently running. Wait for it to finish, then retry.\");\n"
    "      unlockControls();\n"
    "    } else if (xhr.status === 400) {\n"
    "      $(\"progStage\").textContent = \"FAILED\";\n"
    "      showAlert(\"err\", \"Upload rejected (HTTP 400)\",\n"
    "        xhr.responseText || \"Image was rejected. Wrong chip target, truncated, \"\n"
    "        + \"or wrong Content-Type.\");\n"
    "      unlockControls();\n"
    "    } else {\n"
    "      $(\"progStage\").textContent = \"FAILED\";\n"
    "      showAlert(\"err\", \"Upload rejected (HTTP \" + xhr.status + \")\",\n"
    "        xhr.responseText || \"Unknown error\");\n"
    "      unlockControls();\n"
    "    }\n"
    "  });\n"
    "\n"
    "  xhr.addEventListener(\"error\", () => {\n"
    "    $(\"progStage\").textContent = \"ERROR\";\n"
    "    showAlert(\"err\", \"Network error during upload\",\n"
    "      \"The connection was lost. Check the device and try again.\");\n"
    "    unlockControls();\n"
    "  });\n"
    "\n"
    "  xhr.addEventListener(\"abort\", () => {\n"
    "    $(\"progStage\").textContent = \"ABORTED\";\n"
    "    showAlert(\"warn\", \"Upload cancelled\", \"No changes were made.\");\n"
    "    unlockControls();\n"
    "  });\n"
    "\n"
    "  /* IMPORTANT: set the Authorization header BEFORE xhr.send(file). The\n"
    "   * browser will not prompt for credentials in response to a 401 on an XHR\n"
    "   * POST that already carries a body — the body has been consumed and can't\n"
    "   * be replayed. Credentials must be on the first attempt or never. */\n"
    "  xhr.open(\"POST\", \"/api/ota\");\n"
    "  xhr.setRequestHeader(\"Content-Type\", \"application/octet-stream\");\n"
    "  xhr.setRequestHeader(\"Authorization\", \"Basic \" + btoa(user + \":\" + pass));\n"
    "  xhr.send(file);\n"
    "}\n"
    "\n"
    "/* ─── Reboot watcher ─── */\n"
    "async function waitForReboot() {\n"
    "  let tries = 0;\n"
    "  const maxTries = 30;\n"
    "  showAlert(\"info\", \"Waiting for device to come back online&hellip;\", \"\");\n"
    "  const tick = async () => {\n"
    "    tries++;\n"
    "    try {\n"
    "      const r = await fetch(\"/api/ota/info\", { cache: \"no-store\" });\n"
    "      if (r.ok) {\n"
    "        const d = await r.json();\n"
    "        showAlert(\"ok\", \"Device back online \\u2014 new version: \" + (d.app_version || \"?\"),\n"
    "          \"Running from partition <code>\" + (d.running ? d.running.label : \"?\") + \"</code>. \"\n"
    "          + \"<a href='/' style='color:var(--ok)'>Go to status page &rarr;</a>\");\n"
    "        return;\n"
    "      }\n"
    "    } catch (e) { /* device still down, keep polling */ }\n"
    "    if (tries < maxTries) setTimeout(tick, 2000);\n"
    "    else showAlert(\"warn\", \"Device did not respond within 60 s\",\n"
    "      \"Check the serial console. The previous firmware may have been restored automatically \"\n"
    "      + \"if the new image failed health checks.\");\n"
    "  };\n"
    "  tick();\n"
    "}\n"
    "\n"
    "/* Initial load */\n"
    "loadInfo();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    ;

#ifdef __cplusplus
}
#endif

#endif /* OTA_PAGE_H */
