/* ============================================================================
 *  status_page.h  --  Embedded HTML status page for ESP32-P4 PTP Slave
 *
 *  This header embeds, as a single C string literal, a self-contained
 *  HTML / CSS / JavaScript page that renders runtime diagnostics for the
 *  PTPv2 slave running on this device. The page polls /api/status every
 *  5 seconds (XHR/fetch) and updates every field in place.
 *
 *  Project: https://github.com/Montecri/GNSSTimeServer
 *
 *  NOTE: Auto-generated from index.html. Do not edit by hand -- re-run
 *        build_ota_page.py whenever index.html changes, then rebuild & flash.
 * ============================================================================ */

#ifndef STATUS_PAGE_H
#define STATUS_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

static const char STATUS_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<link rel=\"icon\" type=\"image/svg+xml\" href=\"data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2064%2064'%3E%3Ccircle%20cx='32'%20cy='32'%20r='30'%20fill='%232563eb'%20stroke='%2393c5fd'%20stroke-width='2.5'/%3E%3Cg%20stroke='%23dbeafe'%20stroke-width='2.5'%20stroke-linecap='round'%20opacity='0.75'%3E%3Cline%20x1='32'%20y1='7'%20x2='32'%20y2='12'/%3E%3Cline%20x1='32'%20y1='52'%20x2='32'%20y2='57'/%3E%3Cline%20x1='7'%20y1='32'%20x2='12'%20y2='32'/%3E%3Cline%20x1='52'%20y1='32'%20x2='57'%20y2='32'/%3E%3C/g%3E%3Cg%20stroke='%23ffffff'%20stroke-linecap='round'%20fill='none'%3E%3Cpath%20d='M%2032%2032%20L%2023%2026'%20stroke-width='5.5'/%3E%3Cpath%20d='M%2032%2032%20L%2043%2021'%20stroke-width='5'/%3E%3C/g%3E%3Ccircle%20cx='32'%20cy='32'%20r='3.5'%20fill='%23ffffff'/%3E%3C/svg%3E\">\n"
    "<title>PTP Slave &mdash; ESP32-P4</title>\n"
    "<style>\n"
    "  :root {\n"
    "    --bg-0:#0b1018; --bg-1:#121a26; --bg-2:#1a2536; --bg-3:#233047;\n"
    "    --line:#2a3a55; --line-soft:#1f2c42;\n"
    "    --text:#e6edf7; --text-dim:#8fa1bf; --text-mute:#5a6c8a;\n"
    "    --accent:#7aa2f7; --accent-2:#bd93f9;\n"
    "    --ok:#50fa7b; --warn:#ffb86c; --err:#ff5577;\n"
    "    --info:#8be9fd; --purple:#bd93f9; --gold:#f1c40f;\n"
    "    --grid-glow:rgba(122,162,247,0.08);\n"
    "    --mono:ui-monospace,\"SF Mono\",\"JetBrains Mono\",\"Cascadia Code\",Consolas,\"Courier New\",monospace;\n"
    "    --sans:-apple-system,BlinkMacSystemFont,\"Segoe UI\",system-ui,sans-serif;\n"
    "    --emoji:\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Noto Color Emoji\",\"Segoe UI Symbol\",sans-serif;\n"
    "  }\n"
    "  * { box-sizing:border-box; }\n"
    "  html,body { margin:0; padding:0; background:var(--bg-0); color:var(--text); font-family:var(--sans); -webkit-font-smoothing:antialiased; min-height:100vh; }\n"
    "  body {\n"
    "    background:\n"
    "      radial-gradient(circle at 15% 0%, rgba(122,162,247,0.06) 0%, transparent 40%),\n"
    "      radial-gradient(circle at 85% 100%, rgba(189,147,249,0.05) 0%, transparent 40%),\n"
    "      linear-gradient(180deg,var(--bg-0) 0%,#060a12 100%);\n"
    "    background-attachment:fixed;\n"
    "  }\n"
    "  body::before {\n"
    "    content:\"\"; position:fixed; inset:0;\n"
    "    background-image:\n"
    "      linear-gradient(var(--grid-glow) 1px,transparent 1px),\n"
    "      linear-gradient(90deg,var(--grid-glow) 1px,transparent 1px);\n"
    "    background-size:48px 48px; pointer-events:none; z-index:0; opacity:0.4;\n"
    "  }\n"
    "  .container { position:relative; z-index:1; max-width:1280px; margin:0 auto; padding:28px 24px 48px; }\n"
    "\n"
    "  header { display:flex; align-items:center; justify-content:space-between; gap:16px;\n"
    "           padding-bottom:20px; border-bottom:1px solid var(--line-soft); margin-bottom:24px; flex-wrap:wrap; }\n"
    "  .brand { display:flex; align-items:center; gap:14px; }\n"
    "  .brand .mark { width:44px; height:44px; border-radius:10px;\n"
    "                 background:linear-gradient(135deg,var(--accent) 0%,var(--accent-2) 100%);\n"
    "                 display:flex; align-items:center; justify-content:center;\n"
    "                 font-family:var(--mono); font-weight:800; font-size:18px; color:var(--bg-0);\n"
    "                 letter-spacing:-0.5px; box-shadow:0 0 24px rgba(122,162,247,0.3); }\n"
    "  .brand h1 { margin:0; font-size:20px; font-weight:600; letter-spacing:0.2px; }\n"
    "  .brand .sub { margin:2px 0 0; font-family:var(--mono); font-size:11px; color:var(--text-dim); letter-spacing:0.5px; }\n"
    "  .fw-ver { color:var(--accent); font-weight:600; }\n"
    "\n"
    "  .status-pill { display:inline-flex; align-items:center; gap:8px; padding:8px 14px;\n"
    "                 border-radius:999px; background:rgba(80,250,123,0.08);\n"
    "                 border:1px solid rgba(80,250,123,0.3);\n"
    "                 font-family:var(--mono); font-size:12px; letter-spacing:1px; color:var(--ok);\n"
    "                 transition:all 0.3s ease; }\n"
    "  .status-pill.warn { background:rgba(255,184,108,0.08); border-color:rgba(255,184,108,0.3); color:var(--warn); }\n"
    "  .status-pill.warn .dot { background:var(--warn); box-shadow:0 0 8px var(--warn); }\n"
    "  .status-pill.err { background:rgba(255,85,119,0.08); border-color:rgba(255,85,119,0.3); color:var(--err); }\n"
    "  .status-pill.err .dot { background:var(--err); box-shadow:0 0 8px var(--err); }\n"
    "  .status-pill .dot { width:8px; height:8px; border-radius:50%; background:var(--ok);\n"
    "                      box-shadow:0 0 8px var(--ok); animation:pulse 2s ease-in-out infinite; }\n"
    "  @keyframes pulse { 0%,100%{opacity:1;transform:scale(1);} 50%{opacity:0.5;transform:scale(0.85);} }\n"
    "\n"
    "  .grid { display:grid; grid-template-columns:repeat(12,1fr); gap:18px; }\n"
    "  .card { background:linear-gradient(180deg,var(--bg-1) 0%,var(--bg-2) 100%);\n"
    "          border:1px solid var(--line-soft); border-radius:14px; padding:18px 20px;\n"
    "          position:relative; overflow:hidden; transition:border-color 0.2s ease; }\n"
    "  .card:hover { border-color:var(--line); }\n"
    "  .card::before { content:\"\"; position:absolute; top:0; left:0; right:0; height:1px;\n"
    "                  background:linear-gradient(90deg,transparent,var(--line),transparent); }\n"
    "  .card-header { display:flex; align-items:center; justify-content:space-between;\n"
    "                 margin-bottom:14px; padding-bottom:10px; border-bottom:1px dashed var(--line-soft); }\n"
    "  .card-header h2 { margin:0; font-size:11px; font-weight:700; letter-spacing:2px;\n"
    "                    text-transform:uppercase; color:var(--text-dim); }\n"
    "  .card-header .badge { font-family:var(--mono); font-size:10px; color:var(--text-mute); letter-spacing:0.5px; }\n"
    "\n"
    "  .col-3{grid-column:span 3;} .col-4{grid-column:span 4;} .col-5{grid-column:span 5;}\n"
    "  .col-6{grid-column:span 6;} .col-7{grid-column:span 7;} .col-8{grid-column:span 8;}\n"
    "  .col-12{grid-column:span 12;}\n"
    "  @media (max-width:960px){ .col-3,.col-4,.col-5,.col-6,.col-7,.col-8{grid-column:span 12;} }\n"
    "\n"
    "  .rows { display:flex; flex-direction:column; gap:2px; }\n"
    "  .row { display:grid; grid-template-columns:28px 1fr auto; align-items:center; gap:12px;\n"
    "         padding:9px 4px; border-bottom:1px solid transparent; transition:background 0.15s ease; }\n"
    "  .row:hover { background:rgba(255,255,255,0.015); }\n"
    "  .row + .row { border-top:1px solid var(--line-soft); }\n"
    "  .row .icon { font-family:var(--emoji); font-size:18px; line-height:1;\n"
    "               text-align:center; width:28px; display:inline-flex;\n"
    "               align-items:center; justify-content:center; filter:saturate(1.1); }\n"
    "  .row .label { font-size:13px; color:var(--text); font-weight:500; letter-spacing:0.1px; }\n"
    "  .row .label .hint { display:block; font-family:var(--mono); font-size:10px;\n"
    "                      color:var(--text-mute); font-weight:400; margin-top:2px; letter-spacing:0.3px; }\n"
    "  .row .value { font-family:var(--mono); font-size:12.5px; color:var(--text);\n"
    "                text-align:right; font-variant-numeric:tabular-nums;\n"
    "                transition:color 0.3s ease; }\n"
    "  .row .value.dim{color:var(--text-dim);} .row .value.ok{color:var(--ok);}\n"
    "  .row .value.warn{color:var(--warn);} .row .value.err{color:var(--err);}\n"
    "  .row .value.info{color:var(--info);} .row .value.accent{color:var(--accent);}\n"
    "  .row .value.purple{color:var(--purple);}\n"
    "  .row .value.hostname{max-width:220px;min-width:0;overflow-wrap:anywhere;line-height:1.25;}\n"
    "\n"
    "  .chip { display:inline-block; padding:2px 8px; border-radius:4px;\n"
    "          font-family:var(--mono); font-size:11px; letter-spacing:0.5px;\n"
    "          border:1px solid currentColor; background:rgba(255,255,255,0.02); }\n"
    "  .chip.ok{color:var(--ok); background:rgba(80,250,123,0.08);}\n"
    "  .chip.warn{color:var(--warn); background:rgba(255,184,108,0.08);}\n"
    "  .chip.err{color:var(--err); background:rgba(255,85,119,0.08);}\n"
    "  .chip.info{color:var(--info); background:rgba(139,233,253,0.08);}\n"
    "\n"
    "  .hero { grid-column:span 12; display:grid; grid-template-columns:repeat(4,1fr); gap:18px; }\n"
    "  @media (max-width:960px){ .hero{grid-template-columns:repeat(2,1fr);} }\n"
    "  .metric { background:linear-gradient(180deg,var(--bg-1) 0%,var(--bg-2) 100%);\n"
    "            border:1px solid var(--line-soft); border-radius:14px; padding:18px 20px;\n"
    "            position:relative; overflow:hidden; transition:border-color 0.3s ease; }\n"
    "  .metric .metric-head { display:flex; align-items:center; gap:10px; margin-bottom:12px; }\n"
    "  .metric .metric-head .icon { font-family:var(--emoji); font-size:18px; }\n"
    "  .metric .metric-head .label { font-size:10px; letter-spacing:2px; text-transform:uppercase;\n"
    "                                color:var(--text-dim); font-weight:700; }\n"
    "  .metric .big { font-family:var(--mono); font-size:26px; font-weight:700;\n"
    "                 color:var(--text); letter-spacing:-0.5px; line-height:1.1;\n"
    "                 transition:color 0.3s ease; }\n"
    "  .metric .big .unit { font-size:14px; color:var(--text-dim); }\n"
    "  .metric .sub { margin-top:6px; font-family:var(--mono); font-size:11px;\n"
    "                 color:var(--text-mute); letter-spacing:0.3px; }\n"
    "  .metric.locked { border-color:rgba(80,250,123,0.25); }\n"
    "  .metric.locked .big { color:var(--ok); }\n"
    "  .metric.holdover { border-color:rgba(255,184,108,0.25); }\n"
    "  .metric.holdover .big { color:var(--warn); }\n"
    "  .metric.fault, .metric.no-link { border-color:rgba(255,85,119,0.25); }\n"
    "  .metric.fault .big, .metric.no-link .big { color:var(--err); }\n"
    "\n"
    "  .tasks { width:100%; border-collapse:collapse; font-size:12px; font-family:var(--mono); }\n"
    "  .tasks thead th { text-align:left; padding:8px 10px; border-bottom:1px solid var(--line);\n"
    "                    color:var(--text-dim); font-weight:600; font-size:10px;\n"
    "                    letter-spacing:1.5px; text-transform:uppercase; }\n"
    "  .tasks tbody td { padding:7px 10px; border-bottom:1px solid var(--line-soft);\n"
    "                    color:var(--text); font-variant-numeric:tabular-nums; }\n"
    "  .tasks tbody tr:hover { background:rgba(255,255,255,0.02); }\n"
    "  .tasks .tname { display:inline-flex; align-items:center; gap:8px; }\n"
    "  .tasks .tname .icon { font-family:var(--emoji); font-size:14px; }\n"
    "  .prio { display:inline-block; min-width:22px; text-align:center; padding:1px 6px;\n"
    "          border-radius:4px; font-size:11px; font-weight:700; }\n"
    "  .prio.p7{background:rgba(255,85,119,0.15); color:var(--err);}\n"
    "  .prio.p6{background:rgba(255,184,108,0.15); color:var(--warn);}\n"
    "  .prio.p5{background:rgba(241,196,15,0.15); color:var(--gold);}\n"
    "  .prio.p2{background:rgba(139,233,253,0.15); color:var(--info);}\n"
    "  .prio.p1{background:rgba(122,162,247,0.15); color:var(--accent);}\n"
    "  .bar { display:inline-block; width:60px; height:5px; background:var(--bg-3);\n"
    "         border-radius:99px; overflow:hidden; vertical-align:middle; margin-right:8px; }\n"
    "  .bar > i { display:block; height:100%;\n"
    "             background:linear-gradient(90deg,var(--accent),var(--accent-2));\n"
    "             border-radius:99px; transition:width 0.5s ease; }\n"
    "\n"
    "  footer { margin-top:32px; padding-top:16px; border-top:1px solid var(--line-soft);\n"
    "           text-align:center; font-family:var(--mono); font-size:10.5px;\n"
    "           color:var(--text-mute); letter-spacing:1px; }\n"
    "  footer a { color:var(--accent); text-decoration:none; border-bottom:1px dashed transparent;\n"
    "             transition:border-color 0.2s ease; }\n"
    "  footer a:hover { border-bottom-color:var(--accent); }\n"
    "  footer .live { color:var(--accent); margin-left:6px; }\n"
    "  footer .sep { margin:0 8px; color:var(--text-mute); opacity:0.5; }\n"
    "\n"
    "  /* OTA link button in header */\n"
    "  .ota-link {\n"
    "    display:inline-flex; align-items:center; gap:8px;\n"
    "    padding:8px 14px; border-radius:999px;\n"
    "    background:rgba(189,147,249,0.08);\n"
    "    border:1px solid rgba(189,147,249,0.3);\n"
    "    font-family:var(--mono); font-size:12px; letter-spacing:1px;\n"
    "    color:var(--accent-2); text-decoration:none;\n"
    "    transition:all 0.2s ease;\n"
    "    margin-right:8px;\n"
    "  }\n"
    "  .ota-link:hover {\n"
    "    background:rgba(189,147,249,0.15);\n"
    "    border-color:var(--accent-2);\n"
    "    transform:translateY(-1px);\n"
    "  }\n"
    "  .ota-link .icon { font-family:var(--emoji); font-size:14px; }\n"
    "\n"
    "  .header-actions { display:flex; align-items:center; gap:0; flex-wrap:wrap; }\n"
    "\n"
    "  /* fade flash on update */\n"
    "  .flash { animation:flash 0.6s ease; }\n"
    "  @keyframes flash { 0%{background:rgba(122,162,247,0.1);} 100%{background:transparent;} }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"container\">\n"
    "\n"
    "  <header>\n"
    "    <div class=\"brand\">\n"
    "      <div class=\"mark\">P4</div>\n"
    "      <div>\n"
    "        <h1>PTP Slave &mdash; ESP32-P4 Ordinary Clock</h1>\n"
    "        <div class=\"sub\">IEEE 1588-2008 &middot; L2/Ethernet Transport &middot; Domain 0\n"
    "          &middot; <span class=\"fw-ver\" id=\"hdr_fw\">fw &mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div class=\"header-actions\">\n"
    "      <a class=\"ota-link\" href=\"/ota\" title=\"Firmware update\">\n"
    "        <span class=\"icon\">&#x1F680;</span><span>OTA UPDATE</span>\n"
    "      </a>\n"
    "      <div class=\"status-pill\" id=\"hdrStatus\">\n"
    "        <span class=\"dot\"></span><span id=\"hdrStatusText\">CONNECTING&hellip;</span>\n"
    "      </div>\n"
    "    </div>\n"
    "  </header>\n"
    "\n"
    "  <div class=\"grid\">\n"
    "\n"
    "    <!-- HERO METRICS -->\n"
    "    <div class=\"hero\">\n"
    "      <div class=\"metric\" id=\"m_state\">\n"
    "        <div class=\"metric-head\"><span class=\"icon\">&#x1F512;</span><span class=\"label\">Sync State</span></div>\n"
    "        <div class=\"big\" id=\"v_state\">&mdash;</div>\n"
    "        <div class=\"sub\" id=\"v_state_sub\">awaiting first Sync</div>\n"
    "      </div>\n"
    "      <div class=\"metric\">\n"
    "        <div class=\"metric-head\"><span class=\"icon\">&#x1F3AF;</span><span class=\"label\">Offset to GM</span></div>\n"
    "        <div class=\"big\" id=\"v_offset\">&mdash;</div>\n"
    "        <div class=\"sub\" id=\"v_offset_sub\">live PTP offset</div>\n"
    "      </div>\n"
    "      <div class=\"metric\">\n"
    "        <div class=\"metric-head\"><span class=\"icon\">&#x21C4;</span><span class=\"label\">Path Delay</span></div>\n"
    "        <div class=\"big\" id=\"v_pathdelay\">&mdash;</div>\n"
    "        <div class=\"sub\" id=\"v_pathdelay_sub\">one-way</div>\n"
    "      </div>\n"
    "      <div class=\"metric\">\n"
    "        <div class=\"metric-head\"><span class=\"icon\">&#x1F4E1;</span><span class=\"label\">Grandmaster</span></div>\n"
    "        <div class=\"big\" id=\"v_gm\">&mdash;</div>\n"
    "        <div class=\"sub\" id=\"v_gm_sub\">&mdash;</div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- DEVICE -->\n"
    "    <div class=\"card col-4\">\n"
    "      <div class=\"card-header\"><h2>Device</h2><span class=\"badge\" id=\"b_dev\">ESP32-P4</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F9E0;</span>\n"
    "          <span class=\"label\">Chip<span class=\"hint\">Dual RISC-V HP core</span></span>\n"
    "          <span class=\"value\" id=\"v_chip\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x26A1;</span>\n"
    "          <span class=\"label\">CPU Frequency</span>\n"
    "          <span class=\"value accent\" id=\"v_cpufreq\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4E6;</span>\n"
    "          <span class=\"label\">Project<span class=\"hint\" id=\"v_appver\">app version &mdash;</span></span>\n"
    "          <span class=\"value\" id=\"v_proj\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4DD;</span>\n"
    "          <span class=\"label\">ESP-IDF</span>\n"
    "          <span class=\"value\" id=\"v_idf\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F6E0;&#xFE0F;</span>\n"
    "          <span class=\"label\">Compile time</span>\n"
    "          <span class=\"value dim\" id=\"v_compile\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F511;</span>\n"
    "          <span class=\"label\">ELF SHA-256</span>\n"
    "          <span class=\"value dim\" id=\"v_sha\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4BE;</span>\n"
    "          <span class=\"label\">Flash</span>\n"
    "          <span class=\"value\" id=\"v_flash\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F551;</span>\n"
    "          <span class=\"label\">Uptime</span>\n"
    "          <span class=\"value ok\" id=\"v_uptime\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- MEMORY -->\n"
    "    <div class=\"card col-4\">\n"
    "      <div class=\"card-header\"><h2>Memory</h2><span class=\"badge\">internal heap</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F49A;</span>\n"
    "          <span class=\"label\">Free heap<span class=\"hint\">MALLOC_CAP_INTERNAL</span></span>\n"
    "          <span class=\"value ok\" id=\"v_heap_free\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4C9;</span>\n"
    "          <span class=\"label\">Min ever free<span class=\"hint\">low-water mark since boot</span></span>\n"
    "          <span class=\"value warn\" id=\"v_heap_min\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F9F1;</span>\n"
    "          <span class=\"label\">Largest free block</span>\n"
    "          <span class=\"value\" id=\"v_heap_lfb\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F3DB;&#xFE0F;</span>\n"
    "          <span class=\"label\">RETENT_RAM<span class=\"hint\">@ 0x4FF178D0</span></span>\n"
    "          <span class=\"value dim\" id=\"v_retent\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4D0;</span>\n"
    "          <span class=\"label\">RAM regions</span>\n"
    "          <span class=\"value dim\" id=\"v_ram\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F50B;</span>\n"
    "          <span class=\"label\">RTC RAM</span>\n"
    "          <span class=\"value dim\" id=\"v_rtcram\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4BD;</span>\n"
    "          <span class=\"label\">TCM</span>\n"
    "          <span class=\"value dim\" id=\"v_tcm\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x267B;&#xFE0F;</span>\n"
    "          <span class=\"label\">Leak delta<span class=\"hint\">since baseline</span></span>\n"
    "          <span class=\"value ok\" id=\"v_leak\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- NETWORK -->\n"
    "    <div class=\"card col-4\">\n"
    "      <div class=\"card-header\"><h2>Network</h2><span class=\"badge\">EMAC &middot; L2TAP</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F50C;</span>\n"
    "          <span class=\"label\">Link status</span>\n"
    "          <span class=\"value\" id=\"v_link\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F3E0;</span>\n"
    "          <span class=\"label\">Hostname<span class=\"hint\">DHCP / DNS / mDNS identity</span></span>\n"
    "          <span class=\"value accent hostname\" id=\"v_hostname\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F310;</span>\n"
    "          <span class=\"label\">IP address<span class=\"hint\" id=\"v_ip_hint\">&mdash;</span></span>\n"
    "          <span class=\"value info\" id=\"v_ip\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F3F7;&#xFE0F;</span>\n"
    "          <span class=\"label\">MAC address</span>\n"
    "          <span class=\"value dim\" id=\"v_mac\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4E1;</span>\n"
    "          <span class=\"label\">L2TAP<span class=\"hint\">EtherType 0x88F7</span></span>\n"
    "          <span class=\"value\" id=\"v_l2tap\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4EC;</span>\n"
    "          <span class=\"label\">PTP multicast filter</span>\n"
    "          <span class=\"value dim\" id=\"v_mcast\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F501;</span>\n"
    "          <span class=\"label\">EMAC restarts<span class=\"hint\">RX descriptor recovery</span></span>\n"
    "          <span class=\"value\" id=\"v_emac\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F6AB;</span>\n"
    "          <span class=\"label\">Promiscuous</span>\n"
    "          <span class=\"value dim\" id=\"v_promisc\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F6E1;&#xFE0F;</span>\n"
    "          <span class=\"label\">Watchdog<span class=\"hint\">heap pressure recovery</span></span>\n"
    "          <span class=\"value ok\" id=\"v_wdt\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- PTP / SYNCHRONIZATION -->\n"
    "    <div class=\"card col-6\">\n"
    "      <div class=\"card-header\"><h2>PTP &middot; Synchronization</h2><span class=\"badge\">ordinary clock &middot; slave only</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F465;</span>\n"
    "          <span class=\"label\">Role<span class=\"hint\">this device</span></span>\n"
    "          <span class=\"value accent\" id=\"v_role\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F194;</span>\n"
    "          <span class=\"label\">Our clock ID</span>\n"
    "          <span class=\"value dim\" id=\"v_clockid\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F451;</span>\n"
    "          <span class=\"label\">GM MAC<span class=\"hint\">source of selected Announces</span></span>\n"
    "          <span class=\"value\" id=\"v_gm_mac\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F194;</span>\n"
    "          <span class=\"label\">GM clock ID</span>\n"
    "          <span class=\"value dim\" id=\"v_gm_clockid\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F3F7;&#xFE0F;</span>\n"
    "          <span class=\"label\">GM clockClass<span class=\"hint\">7 = holdover &middot; 6 = locked to PRTC</span></span>\n"
    "          <span class=\"value\" id=\"v_gm_class\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F3AF;</span>\n"
    "          <span class=\"label\">GM accuracy</span>\n"
    "          <span class=\"value dim\" id=\"v_gm_accuracy\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F522;</span>\n"
    "          <span class=\"label\">GM priority1 &middot; priority2</span>\n"
    "          <span class=\"value\" id=\"v_gm_prio\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x23F3;</span>\n"
    "          <span class=\"label\">GM TAI&minus;UTC</span>\n"
    "          <span class=\"value\" id=\"v_gm_utc\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F6F0;&#xFE0F;</span>\n"
    "          <span class=\"label\">GM time source</span>\n"
    "          <span class=\"value dim\" id=\"v_gm_src\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- SERVO -->\n"
    "    <div class=\"card col-6\">\n"
    "      <div class=\"card-header\"><h2>Servo &middot; Discipline</h2><span class=\"badge\">freq + step &middot; linreg window 16</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F7E2;</span>\n"
    "          <span class=\"label\">Servo state</span>\n"
    "          <span class=\"value ok\" id=\"v_servo\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F3AF;</span>\n"
    "          <span class=\"label\">Offset mean &middot; sd<span class=\"hint\">last window</span></span>\n"
    "          <span class=\"value\" id=\"v_off_stats\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x21C4;</span>\n"
    "          <span class=\"label\">Path delay mean &middot; sd</span>\n"
    "          <span class=\"value\" id=\"v_dly_stats\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x269B;&#xFE0F;</span>\n"
    "          <span class=\"label\">Frequency adjustment</span>\n"
    "          <span class=\"value\" id=\"v_freq\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4C8;</span>\n"
    "          <span class=\"label\">Linreg slope<span class=\"hint\">GM apparent drift vs slave PHC</span></span>\n"
    "          <span class=\"value\" id=\"v_slope\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x2696;&#xFE0F;</span>\n"
    "          <span class=\"label\">Asymmetry mean<span class=\"hint\">(ms&rarr;sl) &minus; (sl&rarr;ms)</span></span>\n"
    "          <span class=\"value dim\" id=\"v_asy\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x23F1;&#xFE0F;</span>\n"
    "          <span class=\"label\">TC correction m&rarr;s &middot; s&rarr;m<span class=\"hint\">switch residence-time means; 0 on direct cable</span></span>\n"
    "          <span class=\"value dim\" id=\"v_corr\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4CA;</span>\n"
    "          <span class=\"label\">Quality<span class=\"hint\">% of window within &plusmn;100 ns</span></span>\n"
    "          <span class=\"value ok\" id=\"v_qual\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F50D;</span>\n"
    "          <span class=\"label\">PHC residual<span class=\"hint\">long-window offset mean</span></span>\n"
    "          <span class=\"value dim\" id=\"v_phc\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F198;</span>\n"
    "          <span class=\"label\">Locked for &middot; last Sync</span>\n"
    "          <span class=\"value\" id=\"v_lock_age\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- GM DIAGNOSTICS -->\n"
    "    <div class=\"card col-12\">\n"
    "      <div class=\"card-header\"><h2>Grandmaster Diagnostics</h2><span class=\"badge\" id=\"b_gm_diag\">PTP message counters</span></div>\n"
    "      <div class=\"grid\" style=\"gap:14px;\">\n"
    "\n"
    "        <div class=\"card col-4\" style=\"background:transparent;border:1px dashed var(--line-soft);\">\n"
    "          <div class=\"card-header\" style=\"padding-bottom:8px;margin-bottom:10px;\">\n"
    "            <h2 style=\"font-size:10px;\">Message Counts</h2>\n"
    "          </div>\n"
    "          <div class=\"rows\">\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F4E5;</span>\n"
    "              <span class=\"label\">Sync RX</span>\n"
    "              <span class=\"value\" id=\"v_sync_rx\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F4E5;</span>\n"
    "              <span class=\"label\">Follow_Up RX</span>\n"
    "              <span class=\"value\" id=\"v_fu_rx\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F4E5;</span>\n"
    "              <span class=\"label\">Delay_Resp RX</span>\n"
    "              <span class=\"value\" id=\"v_dr_rx\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F4E2;</span>\n"
    "              <span class=\"label\">Announce RX</span>\n"
    "              <span class=\"value\" id=\"v_ann_rx\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F501;</span>\n"
    "              <span class=\"label\">Step mode<span class=\"hint\">two-step &middot; one-step</span></span>\n"
    "              <span class=\"value dim\" id=\"v_step_mode\">&mdash;</span></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"card col-4\" style=\"background:transparent;border:1px dashed var(--line-soft);\">\n"
    "          <div class=\"card-header\" style=\"padding-bottom:8px;margin-bottom:10px;\">\n"
    "            <h2 style=\"font-size:10px;\">Timing Health</h2>\n"
    "          </div>\n"
    "          <div class=\"rows\">\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F4CF;</span>\n"
    "              <span class=\"label\">Sync interval<span class=\"hint\">spacing between Sync RX</span></span>\n"
    "              <span class=\"value\" id=\"v_sync_ivl\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x23F1;&#xFE0F;</span>\n"
    "              <span class=\"label\">Follow_Up latency<span class=\"hint\">Sync RX &rarr; FU RX</span></span>\n"
    "              <span class=\"value\" id=\"v_fu_lat\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x26A0;&#xFE0F;</span>\n"
    "              <span class=\"label\">Sync seq gaps</span>\n"
    "              <span class=\"value\" id=\"v_sync_gap\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x26A0;&#xFE0F;</span>\n"
    "              <span class=\"label\">Announce seq gaps</span>\n"
    "              <span class=\"value\" id=\"v_ann_gap\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F4A5;</span>\n"
    "              <span class=\"label\">Post-lock spikes<span class=\"hint\">|offset| &gt; 1&micro;s after lock</span></span>\n"
    "              <span class=\"value\" id=\"v_spikes\">&mdash;</span></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"card col-4\" style=\"background:transparent;border:1px dashed var(--line-soft);\">\n"
    "          <div class=\"card-header\" style=\"padding-bottom:8px;margin-bottom:10px;\">\n"
    "            <h2 style=\"font-size:10px;\">Integrity</h2>\n"
    "          </div>\n"
    "          <div class=\"rows\">\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F47B;</span>\n"
    "              <span class=\"label\">FollowUp orphans<span class=\"hint\">FU w/o matching Sync</span></span>\n"
    "              <span class=\"value\" id=\"v_fu_orph\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F47B;</span>\n"
    "              <span class=\"label\">DelayResp orphans<span class=\"hint\">DR w/o pending DReq</span></span>\n"
    "              <span class=\"value\" id=\"v_dr_orph\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F500;</span>\n"
    "              <span class=\"label\">GM identity changes<span class=\"hint\">switched grandmaster</span></span>\n"
    "              <span class=\"value\" id=\"v_gm_chg\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F39A;&#xFE0F;</span>\n"
    "              <span class=\"label\">GM class transitions<span class=\"hint\">e.g. 6 &rarr; 7 (holdover)</span></span>\n"
    "              <span class=\"value\" id=\"v_class_chg\">&mdash;</span></div>\n"
    "            <div class=\"row\"><span class=\"icon\">&#x1F50A;</span>\n"
    "              <span class=\"label\">LED heartbeat<span class=\"hint\">Sync RX pulse count</span></span>\n"
    "              <span class=\"value dim\" id=\"v_pulse_seq\">&mdash;</span></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- TASKS -->\n"
    "    <div class=\"card col-12\">\n"
    "      <div class=\"card-header\"><h2>FreeRTOS Tasks</h2><span class=\"badge\" id=\"b_tasks\">&mdash; tasks</span></div>\n"
    "      <table class=\"tasks\">\n"
    "        <thead>\n"
    "          <tr>\n"
    "            <th style=\"width:24%\">Task</th>\n"
    "            <th style=\"width:10%\">Priority</th>\n"
    "            <th style=\"width:14%\">Stack</th>\n"
    "            <th style=\"width:18%\">High-water mark</th>\n"
    "            <th style=\"width:10%\">Core</th>\n"
    "            <th>Role</th>\n"
    "          </tr>\n"
    "        </thead>\n"
    "        <tbody id=\"tasksBody\">\n"
    "          <tr><td colspan=\"6\" style=\"text-align:center; color:var(--text-mute); padding:20px;\">awaiting data&hellip;</td></tr>\n"
    "        </tbody>\n"
    "      </table>\n"
    "    </div>\n"
    "\n"
    "  </div>\n"
    "\n"
    "  <footer>\n"
    "    Last refresh <span class=\"live\" id=\"lastRefresh\">&mdash;</span>\n"
    "    <span class=\"sep\">&middot;</span> auto-refresh every 5000 ms\n"
    "    <span class=\"sep\">&middot;</span>\n"
    "    <a href=\"https://github.com/Montecri/GNSSTimeServer\" target=\"_blank\" rel=\"noopener\">github.com/Montecri/GNSSTimeServer</a>\n"
    "  </footer>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "\"use strict\";\n"
    "\n"
    "/* ─── Icon map for known FreeRTOS task names (slave set) ─── */\n"
    "const TASK_META = {\n"
    "  \"ptp_rx\":         { icon:\"\\u{1F4E5}\", role:\"L2TAP RX, hw timestamps, slave SM\" },\n"
    "  \"delay_req\":      { icon:\"\\u{1F4E4}\", role:\"Delay_Req emitter (queued)\" },\n"
    "  \"gm_diag\":        { icon:\"\\u{1F50D}\", role:\"GM quality diagnostics report\" },\n"
    "  \"slave_led_watch\":{ icon:\"\\u{1F441}\\uFE0F\", role:\"LED state vs Sync arrival\" },\n"
    "  \"pps_led\":        { icon:\"\\u{1F4A1}\", role:\"Sync-RX heartbeat indicator\" },\n"
    "  \"led\":            { icon:\"\\u{1F506}\", role:\"Status LED state machine\" },\n"
    "  \"display\":        { icon:\"\\u{1F4FA}\", role:\"SH1106 OLED \\u00B7 3 screens\" },\n"
    "  \"btn\":            { icon:\"\\u{1F518}\", role:\"Display button \\u00B7 GPIO 1\" },\n"
    "  \"dhcp_fb\":        { icon:\"\\u{1F310}\", role:\"DHCP fallback \\u00B7 15 s timeout\" },\n"
    "  \"heap_mon\":       { icon:\"\\u{1F4CA}\", role:\"Heap watchdog \\u00B7 60 s interval\" },\n"
    "  \"wdt\":            { icon:\"\\u{1F415}\", role:\"Watchdog \\u00B7 EMAC restart logic\" },\n"
    "  \"main\":           { icon:\"\\u{1F3E1}\", role:\"Init & supervision (idle)\" }\n"
    "};\n"
    "\n"
    "/* ─── Helpers ─── */\n"
    "const $ = (id) => document.getElementById(id);\n"
    "const fmtKB = (b) => (b/1024).toFixed(0) + \" KB\";\n"
    "\n"
    "function setText(id, val) {\n"
    "  const el = $(id);\n"
    "  if (!el) return;\n"
    "  if (el.textContent !== String(val)) {\n"
    "    el.textContent = val;\n"
    "  }\n"
    "}\n"
    "\n"
    "function formatUptime(s) {\n"
    "  if (typeof s !== \"number\" || s < 0) return \"\\u2014\";\n"
    "  const d = Math.floor(s / 86400);\n"
    "  const h = Math.floor((s % 86400) / 3600);\n"
    "  const m = Math.floor((s % 3600) / 60);\n"
    "  const sec = s % 60;\n"
    "  const pad = (n) => String(n).padStart(2, \"0\");\n"
    "  if (d > 0) return d + \"d \" + pad(h) + \"h\" + pad(m) + \"m\";\n"
    "  return pad(h) + \":\" + pad(m) + \":\" + pad(sec);\n"
    "}\n"
    "\n"
    "/* Format ns/µs/ms based on magnitude */\n"
    "function fmtNs(ns) {\n"
    "  if (typeof ns !== \"number\") return \"\\u2014\";\n"
    "  const sign = ns >= 0 ? \"+\" : \"\";\n"
    "  const a = Math.abs(ns);\n"
    "  if (a < 10000) return sign + ns + \" ns\";\n"
    "  if (a < 10000000) return sign + (ns/1000).toFixed(1) + \" \\u00B5s\";\n"
    "  return sign + (ns/1000000).toFixed(2) + \" ms\";\n"
    "}\n"
    "\n"
    "/* Format µs with smart unit promotion (used for sync intervals) */\n"
    "function fmtUs(us) {\n"
    "  if (typeof us !== \"number\") return \"\\u2014\";\n"
    "  const a = Math.abs(us);\n"
    "  if (a < 10000) return us + \" \\u00B5s\";\n"
    "  return (us / 1000).toFixed(1) + \" ms\";\n"
    "}\n"
    "\n"
    "function prioClass(p) {\n"
    "  if (p >= 7) return \"prio p7\";\n"
    "  if (p === 6) return \"prio p6\";\n"
    "  if (p === 5) return \"prio p5\";\n"
    "  if (p === 2) return \"prio p2\";\n"
    "  return \"prio p1\";\n"
    "}\n"
    "\n"
    "/* Severity styling helper for \"gap\" / \"orphan\" / \"spike\" counters: they\n"
    " * should be green at 0, info at small counts, warn/err if growing. */\n"
    "function counterClass(n, warn_at, err_at) {\n"
    "  if (n == null) return \"value dim\";\n"
    "  if (n === 0) return \"value ok\";\n"
    "  if (n >= err_at) return \"value err\";\n"
    "  if (n >= warn_at) return \"value warn\";\n"
    "  return \"value info\";\n"
    "}\n"
    "\n"
    "/* ─── Main render ─── */\n"
    "function render(d) {\n"
    "  /* Header status pill */\n"
    "  const pill = $(\"hdrStatus\");\n"
    "  const stateUp = (d.servo_state || \"\").toUpperCase();\n"
    "  if (stateUp === \"LOCKED\") pill.className = \"status-pill\";\n"
    "  else if (stateUp === \"HOLDOVER\" || stateUp === \"ACQUIRING\") pill.className = \"status-pill warn\";\n"
    "  else pill.className = \"status-pill err\";\n"
    "  setText(\"hdrStatusText\", \"SLAVE \" + (stateUp || \"?\"));\n"
    "\n"
    "  /* Hero — Sync state */\n"
    "  const mState = $(\"m_state\");\n"
    "  mState.className = \"metric\";\n"
    "  if (stateUp === \"LOCKED\") mState.classList.add(\"locked\");\n"
    "  else if (stateUp === \"HOLDOVER\") mState.classList.add(\"holdover\");\n"
    "  else if (stateUp === \"FAULT\") mState.classList.add(\"fault\");\n"
    "  else if (stateUp === \"NO_LINK\" || stateUp === \"NO LINK\") mState.classList.add(\"no-link\");\n"
    "  setText(\"v_state\", stateUp || \"\\u2014\");\n"
    "  setText(\"v_state_sub\", d.locked_for ? (\"held \" + d.locked_for) : \"awaiting first Sync\");\n"
    "\n"
    "  /* Hero — Offset to GM */\n"
    "  if (typeof d.offset_ns === \"number\" && (stateUp === \"LOCKED\" || stateUp === \"HOLDOVER\")) {\n"
    "    const sign = d.offset_ns >= 0 ? \"+\" : \"\";\n"
    "    $(\"v_offset\").innerHTML = sign + d.offset_ns + ' <span class=\"unit\">ns</span>';\n"
    "  } else {\n"
    "    setText(\"v_offset\", \"\\u2014\");\n"
    "  }\n"
    "  if (typeof d.offset_mean_ns === \"number\" && typeof d.offset_sd_ns === \"number\") {\n"
    "    setText(\"v_offset_sub\", \"mean \" + fmtNs(d.offset_mean_ns) + \" sd \" + Math.round(d.offset_sd_ns) + \" ns\");\n"
    "  } else {\n"
    "    setText(\"v_offset_sub\", \"live PTP offset\");\n"
    "  }\n"
    "\n"
    "  /* Hero — Path delay */\n"
    "  if (typeof d.path_delay_ns === \"number\" && d.path_delay_ns > 0) {\n"
    "    $(\"v_pathdelay\").innerHTML = d.path_delay_ns + ' <span class=\"unit\">ns</span>';\n"
    "  } else {\n"
    "    setText(\"v_pathdelay\", \"\\u2014\");\n"
    "  }\n"
    "  if (typeof d.delay_mean_ns === \"number\" && typeof d.delay_sd_ns === \"number\") {\n"
    "    setText(\"v_pathdelay_sub\", \"mean \" + Math.round(d.delay_mean_ns) + \" ns sd \" + Math.round(d.delay_sd_ns));\n"
    "  } else {\n"
    "    setText(\"v_pathdelay_sub\", \"one-way\");\n"
    "  }\n"
    "\n"
    "  /* Hero — Grandmaster */\n"
    "  if (d.gm_mac && d.gm_mac !== \"00:00:00:00:00:00\") {\n"
    "    /* Show short form: last 4 bytes */\n"
    "    const parts = d.gm_mac.split(\":\");\n"
    "    if (parts.length === 6) {\n"
    "      setText(\"v_gm\", \"..\\u200B\" + parts.slice(2).join(\":\"));\n"
    "    } else {\n"
    "      setText(\"v_gm\", d.gm_mac);\n"
    "    }\n"
    "    $(\"v_gm\").style.color = \"var(--text)\";\n"
    "  } else {\n"
    "    setText(\"v_gm\", \"NO GM\");\n"
    "    $(\"v_gm\").style.color = \"var(--err)\";\n"
    "  }\n"
    "  if (typeof d.gm_class === \"number\") {\n"
    "    setText(\"v_gm_sub\", \"class \" + d.gm_class + \" \\u00B7 \" + (d.sync_rx_count || 0).toLocaleString() + \" Sync RX\");\n"
    "  } else {\n"
    "    setText(\"v_gm_sub\", \"no Announce yet\");\n"
    "  }\n"
    "\n"
    "  /* Device */\n"
    "  setText(\"v_chip\", (d.chip || \"ESP32-P4\") + \" rev \" + (d.chip_rev || \"v1.0\"));\n"
    "  setText(\"b_dev\", (d.chip || \"ESP32-P4\") + \" \\u00B7 rev \" + (d.chip_rev || \"v1.0\"));\n"
    "  setText(\"v_cpufreq\", (d.cpu_mhz || 0) + \" MHz\");\n"
    "  setText(\"v_proj\", d.project || \"\\u2014\");\n"
    "  setText(\"v_appver\", \"app version \" + (d.app_version || \"\\u2014\"));\n"
    "  setText(\"hdr_fw\", \"fw \" + (d.app_version || \"\\u2014\"));\n"
    "  setText(\"v_idf\", d.idf_version || \"\\u2014\");\n"
    "  setText(\"v_compile\", d.compile_time || \"\\u2014\");\n"
    "  setText(\"v_sha\", (d.elf_sha || \"\").substring(0,9) + \"\\u2026\");\n"
    "  setText(\"v_flash\", (d.flash_mb || 16) + \" MB \\u00B7 \" + (d.flash_mode || \"DIO\") + \" \\u00B7 \" + (d.flash_mhz || 80) + \" MHz\");\n"
    "  setText(\"v_uptime\", formatUptime(d.uptime_s || 0));\n"
    "\n"
    "  /* Memory */\n"
    "  setText(\"v_heap_free\", fmtKB(d.heap_free || 0));\n"
    "  setText(\"v_heap_min\",  fmtKB(d.heap_min  || 0));\n"
    "  setText(\"v_heap_lfb\",  fmtKB(d.heap_lfb  || 0));\n"
    "  setText(\"v_retent\",    (d.retent_kb || 141) + \" KiB\");\n"
    "  setText(\"v_ram\",       (d.ram1_kb || 384) + \" + \" + (d.ram2_kb || 18) + \" KiB\");\n"
    "  setText(\"v_rtcram\",    (d.rtc_kb || 31) + \" KiB\");\n"
    "  setText(\"v_tcm\",       (d.tcm_kb || 7) + \" KiB\");\n"
    "  if (typeof d.heap_leak === \"number\") {\n"
    "    const lv = $(\"v_leak\");\n"
    "    const sign = d.heap_leak >= 0 ? \"+\" : \"\";\n"
    "    setText(\"v_leak\", sign + d.heap_leak + \" B\");\n"
    "    lv.className = \"value \" + (Math.abs(d.heap_leak) > 1024 ? \"warn\" : \"ok\");\n"
    "  }\n"
    "\n"
    "  /* Network */\n"
    "  const linkUp = !!d.link_up;\n"
    "  $(\"v_link\").innerHTML = linkUp ? '<span class=\"chip ok\">UP</span>' : '<span class=\"chip err\">DOWN</span>';\n"
    "  setText(\"v_hostname\", d.hostname || \"\\u2014\");\n"
    "  if (d.hostname) document.title = d.hostname + \" \\u2014 PTP Slave\";\n"
    "  setText(\"v_ip\", d.ip || \"(no IP)\");\n"
    "  setText(\"v_ip_hint\", d.ip_source ? d.ip_source : \"DHCP/static\");\n"
    "  setText(\"v_mac\", d.mac || \"\\u2014\");\n"
    "  $(\"v_l2tap\").innerHTML = d.l2tap_ready ? '<span class=\"chip ok\">READY</span>' : '<span class=\"chip err\">NOT READY</span>';\n"
    "  setText(\"v_mcast\", \"01:1B:19:00:00:00\");\n"
    "  const emacV = $(\"v_emac\");\n"
    "  setText(\"v_emac\", d.emac_restarts != null ? d.emac_restarts : \"\\u2014\");\n"
    "  emacV.className = \"value \" + ((d.emac_restarts || 0) === 0 ? \"ok\" : (d.emac_restarts > 5 ? \"err\" : \"warn\"));\n"
    "  setText(\"v_promisc\", d.promiscuous ? \"enabled\" : \"disabled\");\n"
    "  setText(\"v_wdt\", d.wdt_healthy ? \"healthy\" : \"alerting\");\n"
    "  $(\"v_wdt\").className = \"value \" + (d.wdt_healthy ? \"ok\" : \"err\");\n"
    "\n"
    "  /* PTP / Synchronization */\n"
    "  setText(\"v_role\", d.role || \"\\u2014\");\n"
    "  setText(\"v_clockid\", d.clock_id || \"\\u2014\");\n"
    "  setText(\"v_gm_mac\", d.gm_mac || \"\\u2014\");\n"
    "  setText(\"v_gm_clockid\", d.gm_clock_id || \"\\u2014\");\n"
    "  if (typeof d.gm_class === \"number\") {\n"
    "    let cls = \"value\";\n"
    "    if (d.gm_class === 6) cls = \"value ok\";        /* locked to primary reference */\n"
    "    else if (d.gm_class === 7) cls = \"value warn\"; /* in holdover */\n"
    "    else if (d.gm_class >= 13 && d.gm_class <= 14) cls = \"value info\"; /* alternate */\n"
    "    $(\"v_gm_class\").textContent = d.gm_class;\n"
    "    $(\"v_gm_class\").className = cls;\n"
    "  } else {\n"
    "    setText(\"v_gm_class\", \"\\u2014\");\n"
    "  }\n"
    "  setText(\"v_gm_accuracy\", typeof d.gm_accuracy === \"number\" ? (\"0x\" + d.gm_accuracy.toString(16).toUpperCase().padStart(2,\"0\")) : \"\\u2014\");\n"
    "  setText(\"v_gm_prio\", (typeof d.gm_priority1 === \"number\" ? d.gm_priority1 : \"?\") + \" \\u00B7 \" +\n"
    "                       (typeof d.gm_priority2 === \"number\" ? d.gm_priority2 : \"?\"));\n"
    "  setText(\"v_gm_utc\", typeof d.gm_utc_offset === \"number\" ? ((d.gm_utc_offset >= 0 ? \"+\" : \"\") + d.gm_utc_offset + \" s\") : \"\\u2014\");\n"
    "  setText(\"v_gm_src\", typeof d.gm_time_source === \"number\" ? (\"0x\" + d.gm_time_source.toString(16).toUpperCase().padStart(2,\"0\")) : \"\\u2014\");\n"
    "\n"
    "  /* Servo */\n"
    "  setText(\"v_servo\", stateUp);\n"
    "  const sv = $(\"v_servo\");\n"
    "  sv.className = \"value \" + (stateUp === \"LOCKED\" ? \"ok\" :\n"
    "                              stateUp === \"HOLDOVER\" ? \"warn\" :\n"
    "                              stateUp === \"FAULT\" || stateUp === \"NO_LINK\" ? \"err\" : \"\");\n"
    "  if (typeof d.offset_mean_ns === \"number\" && typeof d.offset_sd_ns === \"number\" && d.offset_window > 0) {\n"
    "    setText(\"v_off_stats\", fmtNs(d.offset_mean_ns) + \" \\u00B1 \" + Math.round(d.offset_sd_ns) + \" ns (n=\" + d.offset_window + \")\");\n"
    "  } else {\n"
    "    setText(\"v_off_stats\", \"\\u2014\");\n"
    "  }\n"
    "  if (typeof d.delay_mean_ns === \"number\" && typeof d.delay_sd_ns === \"number\" && d.delay_window > 0) {\n"
    "    setText(\"v_dly_stats\", Math.round(d.delay_mean_ns) + \" \\u00B1 \" + Math.round(d.delay_sd_ns) + \" ns (n=\" + d.delay_window + \")\");\n"
    "  } else {\n"
    "    setText(\"v_dly_stats\", \"\\u2014\");\n"
    "  }\n"
    "  if (typeof d.freq_ppb === \"number\") {\n"
    "    const sign = d.freq_ppb >= 0 ? \"+\" : \"\";\n"
    "    setText(\"v_freq\", sign + d.freq_ppb.toFixed(1) + \" ppb\");\n"
    "  } else {\n"
    "    setText(\"v_freq\", \"\\u2014\");\n"
    "  }\n"
    "  if (typeof d.linreg_slope_ppb === \"number\") {\n"
    "    const sign = d.linreg_slope_ppb >= 0 ? \"+\" : \"\";\n"
    "    setText(\"v_slope\", sign + d.linreg_slope_ppb.toFixed(1) + \" ppb\");\n"
    "  } else {\n"
    "    setText(\"v_slope\", \"\\u2014\");\n"
    "  }\n"
    "  if (typeof d.asymmetry_ns === \"number\" && d.asymmetry_n > 0) {\n"
    "    const sign = d.asymmetry_ns >= 0 ? \"+\" : \"\";\n"
    "    setText(\"v_asy\", sign + d.asymmetry_ns + \" ns (n=\" + d.asymmetry_n + \")\");\n"
    "  } else {\n"
    "    setText(\"v_asy\", \"\\u2014\");\n"
    "  }\n"
    "  if (typeof d.corr_m2s_ns === \"number\" && typeof d.corr_s2m_ns === \"number\" && d.asymmetry_n > 0) {\n"
    "    /* fmtNs auto-scales ns -> \\u00B5s -> ms, same rule as the other rows */\n"
    "    setText(\"v_corr\", fmtNs(d.corr_m2s_ns) + \" \\u00B7 \" + fmtNs(d.corr_s2m_ns));\n"
    "  } else {\n"
    "    setText(\"v_corr\", \"\\u2014\");\n"
    "  }\n"
    "  if (typeof d.quality_pct === \"number\") {\n"
    "    setText(\"v_qual\", d.quality_pct + \"%\");\n"
    "    $(\"v_qual\").className = \"value \" + (d.quality_pct >= 80 ? \"ok\" : d.quality_pct >= 50 ? \"warn\" : \"err\");\n"
    "  } else {\n"
    "    setText(\"v_qual\", \"\\u2014\");\n"
    "  }\n"
    "  setText(\"v_phc\", d.phc_residual_ns != null ? ((d.phc_residual_ns >= 0 ? \"+\" : \"\") + d.phc_residual_ns + \" ns\") : \"\\u2014\");\n"
    "  if (d.locked_for && d.locked_for !== \"00:00:00\") {\n"
    "    let txt = \"locked \" + d.locked_for;\n"
    "    if (typeof d.last_sync_age_ms === \"number\") {\n"
    "      txt += \" \\u00B7 sync \" + (d.last_sync_age_ms / 1000).toFixed(1) + \"s ago\";\n"
    "    }\n"
    "    setText(\"v_lock_age\", txt);\n"
    "  } else if (typeof d.last_sync_age_ms === \"number\") {\n"
    "    setText(\"v_lock_age\", \"sync \" + (d.last_sync_age_ms / 1000).toFixed(1) + \"s ago\");\n"
    "  } else {\n"
    "    setText(\"v_lock_age\", \"\\u2014\");\n"
    "  }\n"
    "\n"
    "  /* GM Diagnostics — counters */\n"
    "  setText(\"v_sync_rx\", (d.sync_rx_count != null ? d.sync_rx_count.toLocaleString() : \"\\u2014\"));\n"
    "  setText(\"v_fu_rx\",   (d.followup_rx_count != null ? d.followup_rx_count.toLocaleString() : \"\\u2014\"));\n"
    "  setText(\"v_dr_rx\",   (d.delay_resp_rx_count != null ? d.delay_resp_rx_count.toLocaleString() : \"\\u2014\"));\n"
    "  setText(\"v_ann_rx\",  (d.announce_rx_count != null ? d.announce_rx_count.toLocaleString() : \"\\u2014\"));\n"
    "  /* Step mode badge */\n"
    "  let mode = \"?\";\n"
    "  if (typeof d.two_step_count === \"number\" && typeof d.one_step_count === \"number\") {\n"
    "    if (d.two_step_count > 0 && d.one_step_count === 0)      mode = \"two-step\";\n"
    "    else if (d.one_step_count > 0 && d.two_step_count === 0) mode = \"one-step\";\n"
    "    else if (d.two_step_count > 0 && d.one_step_count > 0)   mode = \"mixed\";\n"
    "    else                                                       mode = \"none\";\n"
    "  }\n"
    "  setText(\"v_step_mode\", mode);\n"
    "\n"
    "  /* Timing health */\n"
    "  if (typeof d.sync_ivl_mean_us === \"number\" && d.sync_ivl_window > 0) {\n"
    "    setText(\"v_sync_ivl\", fmtUs(d.sync_ivl_mean_us) + \" (n=\" + d.sync_ivl_window + \")\");\n"
    "  } else {\n"
    "    setText(\"v_sync_ivl\", \"\\u2014\");\n"
    "  }\n"
    "  if (typeof d.fu_latency_mean_us === \"number\" && d.fu_latency_window > 0) {\n"
    "    setText(\"v_fu_lat\", fmtUs(d.fu_latency_mean_us) + \" (n=\" + d.fu_latency_window + \")\");\n"
    "  } else {\n"
    "    setText(\"v_fu_lat\", \"\\u2014\");\n"
    "  }\n"
    "  setText(\"v_sync_gap\", d.sync_seq_gaps != null ? d.sync_seq_gaps : \"\\u2014\");\n"
    "  $(\"v_sync_gap\").className = counterClass(d.sync_seq_gaps, 1, 10);\n"
    "  setText(\"v_ann_gap\", d.announce_seq_gaps != null ? d.announce_seq_gaps : \"\\u2014\");\n"
    "  $(\"v_ann_gap\").className = counterClass(d.announce_seq_gaps, 1, 10);\n"
    "  setText(\"v_spikes\", d.post_lock_spikes != null ? d.post_lock_spikes : \"\\u2014\");\n"
    "  $(\"v_spikes\").className = counterClass(d.post_lock_spikes, 1, 20);\n"
    "\n"
    "  /* Integrity */\n"
    "  setText(\"v_fu_orph\", d.followup_orphans != null ? d.followup_orphans : \"\\u2014\");\n"
    "  $(\"v_fu_orph\").className = counterClass(d.followup_orphans, 1, 10);\n"
    "  setText(\"v_dr_orph\", d.delay_resp_orphans != null ? d.delay_resp_orphans : \"\\u2014\");\n"
    "  $(\"v_dr_orph\").className = counterClass(d.delay_resp_orphans, 1, 10);\n"
    "  setText(\"v_gm_chg\", d.gm_identity_changes != null ? d.gm_identity_changes : \"\\u2014\");\n"
    "  $(\"v_gm_chg\").className = counterClass(d.gm_identity_changes, 1, 5);\n"
    "  setText(\"v_class_chg\", d.gm_class_transitions != null ? d.gm_class_transitions : \"\\u2014\");\n"
    "  $(\"v_class_chg\").className = counterClass(d.gm_class_transitions, 1, 5);\n"
    "  setText(\"v_pulse_seq\", d.sync_pulse_seq != null ? d.sync_pulse_seq.toLocaleString() : \"\\u2014\");\n"
    "\n"
    "  /* Tasks */\n"
    "  if (Array.isArray(d.tasks)) {\n"
    "    const body = $(\"tasksBody\");\n"
    "    setText(\"b_tasks\", d.tasks.length + \" active \\u00B7 multicore\");\n"
    "    body.innerHTML = d.tasks.map(t => {\n"
    "      const meta = TASK_META[t.name] || { icon: \"\\u{1F539}\", role: \"\\u2014\" };\n"
    "      const used = (t.stack_bytes && t.hwm_bytes != null)\n"
    "                 ? Math.round(100 * (1 - t.hwm_bytes / t.stack_bytes))\n"
    "                 : 0;\n"
    "      const usedBytes = (t.stack_bytes != null && t.hwm_bytes != null)\n"
    "                      ? (t.stack_bytes - t.hwm_bytes)\n"
    "                      : 0;\n"
    "      const usedDisp = usedBytes >= 1024\n"
    "                     ? (usedBytes/1024).toFixed(1) + \" KB\"\n"
    "                     : usedBytes + \" B\";\n"
    "      return \"\"\n"
    "        + \"<tr>\"\n"
    "        + '<td><span class=\"tname\"><span class=\"icon\">' + meta.icon + \"</span>\" + t.name + \"</span></td>\"\n"
    "        + '<td><span class=\"' + prioClass(t.priority) + '\">' + t.priority + \"</span></td>\"\n"
    "        + \"<td>\" + (t.stack_bytes != null ? t.stack_bytes + \" B\" : \"\\u2014\") + \"</td>\"\n"
    "        + '<td><span class=\"bar\"><i style=\"width:' + used + '%\"></i></span>' + usedDisp + \"</td>\"\n"
    "        + \"<td>\" + (t.core != null ? t.core : \"\\u2014\") + \"</td>\"\n"
    "        + \"<td>\" + meta.role + \"</td>\"\n"
    "        + \"</tr>\";\n"
    "    }).join(\"\");\n"
    "  }\n"
    "\n"
    "  /* Footer timestamp */\n"
    "  const now = new Date();\n"
    "  const pad = (n) => String(n).padStart(2, \"0\");\n"
    "  setText(\"lastRefresh\", pad(now.getUTCHours()) + \":\" + pad(now.getUTCMinutes()) + \":\" + pad(now.getUTCSeconds()) + \" UTC\");\n"
    "}\n"
    "\n"
    "/* ─── Polling ─── */\n"
    "async function poll() {\n"
    "  try {\n"
    "    const r = await fetch(\"/api/status\", { cache: \"no-store\" });\n"
    "    if (!r.ok) throw new Error(\"HTTP \" + r.status);\n"
    "    const d = await r.json();\n"
    "    render(d);\n"
    "  } catch (err) {\n"
    "    const pill = $(\"hdrStatus\");\n"
    "    pill.className = \"status-pill err\";\n"
    "    setText(\"hdrStatusText\", \"CONN LOST\");\n"
    "    console.warn(\"poll failed:\", err);\n"
    "  }\n"
    "}\n"
    "\n"
    "poll();\n"
    "setInterval(poll, 5000);\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    ;

#ifdef __cplusplus
}
#endif

#endif /* STATUS_PAGE_H */
