/* AUTOGENERATED - DO NOT EDIT */
/* Declares the data types used by name_data.c's word tables and
 * exposes them (plus the Feistel round keys) to mac_hostname.c, which
 * does the actual MAC <-> hostname encode/decode. See the comment
 * block at the top of name_data.c for how the word tables are laid
 * out and how a MAC address maps onto the 4 hostname tokens. */
#pragma once
#include <stdint.h>
#define N_LAYERS  4   /* one "layer" per hostname token: prefix, title, given, surname */
#define N_ROUNDS  4   /* number of Feistel rounds used to scramble the MAC bits */

/* Describes one hostname token's word table. A token is built from a
 * "stem" (pro_*) optionally followed by an "ending" (deu_*) - e.g.
 * stem "marc" + ending "" -> "marc", or stem "a" + ending "ren" ->
 * "aren". Tokens with no ending (prefix, title) just use a 1-entry
 * empty ending table (deu_count == 1, deu_bits == 0). */
typedef struct {
    const char     *pro_data;     /* stem words, NUL-separated               */
    const uint16_t *pro_offsets;  /* byte offset of each stem word in pro_data */
    uint16_t        pro_count;    /* how many stem words                     */
    const char     *deu_data;     /* ending words, NUL-separated             */
    const uint16_t *deu_offsets;  /* byte offset of each ending word         */
    uint16_t        deu_count;    /* how many ending words                   */
    uint8_t         deu_bits;     /* bits of this layer's index used to pick the ending */
    uint8_t         bits;         /* total bits this layer takes from the 48-bit MAC value */
} name_layer_t;

/* The 4 word tables, one per hostname token, in left-to-right order
 * (prefix, title, given, surname). Defined in name_data.c. */
extern const name_layer_t NAME_LAYERS[N_LAYERS];
/* Fixed constants that drive the Feistel permutation in
 * mac_hostname.c, which mixes the MAC's bits before splitting them
 * across the 4 layers above (so similar MACs don't produce similar-
 * looking hostnames). Defined in name_data.c. */
extern const uint32_t     ROUND_KEYS[N_ROUNDS];
