/* ============================================================================
 *  status_page.h  --  Embedded HTML status page for ESP32-P4 PTP Grandmaster
 *
 *  This header embeds, as a single C raw-string literal, a self-contained
 *  HTML / CSS / JavaScript page that renders runtime diagnostics for the
 *  PTPv2 master running on this device. The page polls "/api/status" every
 *  5 seconds (XHR/fetch) and updates every field in place.
 *
 *  Integration (add to main.c):
 *
 *      #include "status_page.h"
 *      #include "esp_http_server.h"
 *      ...
 *      static esp_err_t root_handler(httpd_req_t *req) {
 *          httpd_resp_set_type(req, "text/html; charset=utf-8");
 *          return httpd_resp_send(req, STATUS_PAGE_HTML, HTTPD_RESP_USE_STRLEN);
 *      }
 *      static esp_err_t status_handler(httpd_req_t *req) {
 *          // Build JSON from your globals and send it. See the JSON contract
 *          // documented at the bottom of this file.
 *      }
 *      static void start_webserver(void) {
 *          httpd_handle_t s = NULL;
 *          httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
 *          if (httpd_start(&s, &cfg) == ESP_OK) {
 *              httpd_uri_t root   = { .uri="/",            .method=HTTP_GET, .handler=root_handler   };
 *              httpd_uri_t status = { .uri="/api/status",  .method=HTTP_GET, .handler=status_handler };
 *              httpd_register_uri_handler(s, &root);
 *              httpd_register_uri_handler(s, &status);
 *          }
 *      }
 *
 *  Project: https://github.com/Montecri/GNSSTimeServer
 *  Target : ESP32-P4-Function-EV-Board, ESP-IDF v5.5.4
 * ============================================================================ */

#ifndef STATUS_PAGE_H
#define STATUS_PAGE_H

/* ── On-page "Load / Soak" monitor poll interval (milliseconds) ──
 * The health poller is OFF by default and only runs after the user clicks
 * "Start monitoring" on the page, so the page never self-loads the device
 * unless opted in. This value sets the cadence used once started. Override at
 * build time, e.g. idf.py build -DHEALTH_POLL_INTERVAL_MS=500, or change the
 * default here. */
#ifndef HEALTH_POLL_INTERVAL_MS
#define HEALTH_POLL_INTERVAL_MS 1000
#endif
/* Stringize so the numeric #define can be concatenated into the embedded JS. */
#define SP_STR2(x) #x
#define SP_STR(x) SP_STR2(x)

#ifdef __cplusplus
extern "C" {
#endif

/* C99 raw-string-equivalent: we use a long C-string built from the source
 * HTML at generate time. Because C has no built-in raw-string literal, the
 * HTML below has been pre-processed: backslashes and double-quotes inside
 * the page are escaped. The page itself is otherwise unmodified. */
static const char STATUS_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<link rel=\"icon\" type=\"image/svg+xml\" href=\"data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2064%2064'%3E%3Ccircle%20cx='32'%20cy='32'%20r='30'%20fill='%2316a34a'%20stroke='%2386efac'%20stroke-width='2.5'/%3E%3Cg%20stroke='%23dcfce7'%20stroke-width='2.5'%20stroke-linecap='round'%20opacity='0.75'%3E%3Cline%20x1='32'%20y1='7'%20x2='32'%20y2='12'/%3E%3Cline%20x1='32'%20y1='52'%20x2='32'%20y2='57'/%3E%3Cline%20x1='7'%20y1='32'%20x2='12'%20y2='32'/%3E%3Cline%20x1='52'%20y1='32'%20x2='57'%20y2='32'/%3E%3C/g%3E%3Cg%20stroke='%23ffffff'%20stroke-linecap='round'%20fill='none'%3E%3Cpath%20d='M%2032%2032%20L%2023%2026'%20stroke-width='5.5'/%3E%3Cpath%20d='M%2032%2032%20L%2043%2021'%20stroke-width='5'/%3E%3C/g%3E%3Ccircle%20cx='32'%20cy='32'%20r='3.5'%20fill='%23ffffff'/%3E%3C/svg%3E\">\n"
    "<title>PTP Master &mdash; ESP32-P4</title>\n"
    "<style>\n"
    "  :root {\n"
    "    --bg-0:#0b1018; --bg-1:#121a26; --bg-2:#1a2536; --bg-3:#233047;\n"
    "    --line:#2a3a55; --line-soft:#1f2c42;\n"
    "    --text:#e6edf7; --text-dim:#8fa1bf; --text-mute:#5a6c8a;\n"
    "    --accent:#4ec9b0; --accent-2:#7aa2f7;\n"
    "    --ok:#50fa7b; --warn:#ffb86c; --err:#ff5577;\n"
    "    --info:#8be9fd; --purple:#bd93f9; --gold:#f1c40f;\n"
    "    --grid-glow:rgba(78,201,176,0.08);\n"
    "    --mono:ui-monospace,\"SF Mono\",\"JetBrains Mono\",\"Cascadia Code\",Consolas,\"Courier New\",monospace;\n"
    "    --sans:-apple-system,BlinkMacSystemFont,\"Segoe UI\",system-ui,sans-serif;\n"
    "    --emoji:\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Noto Color Emoji\",\"Segoe UI Symbol\",sans-serif;\n"
    "  }\n"
    "  * { box-sizing:border-box; }\n"
    "  html,body { margin:0; padding:0; background:var(--bg-0); color:var(--text); font-family:var(--sans); -webkit-font-smoothing:antialiased; min-height:100vh; }\n"
    "  body {\n"
    "    background:\n"
    "      radial-gradient(circle at 15% 0%, rgba(78,201,176,0.06) 0%, transparent 40%),\n"
    "      radial-gradient(circle at 85% 100%, rgba(122,162,247,0.05) 0%, transparent 40%),\n"
    "      linear-gradient(180deg,var(--bg-0) 0%,#060a12 100%);\n"
    "    background-attachment:fixed;\n"
    "  }\n"
    "  body::before {\n"
    "    content:\"\"; position:fixed; inset:0;\n"
    "    background-image:\n"
    "      linear-gradient(var(--grid-glow) 1px,transparent 1px),\n"
    "      linear-gradient(90deg,var(--grid-glow) 1px,transparent 1px);\n"
    "    background-size:48px 48px; pointer-events:none; z-index:0; opacity:0.4;\n"
    "  }\n"
    "  .container { position:relative; z-index:1; max-width:1280px; margin:0 auto; padding:28px 24px 48px; }\n"
    "\n"
    "  header { display:flex; align-items:center; justify-content:space-between; gap:16px;\n"
    "           padding-bottom:20px; border-bottom:1px solid var(--line-soft); margin-bottom:24px; flex-wrap:wrap; }\n"
    "  .brand { display:flex; align-items:center; gap:14px; }\n"
    "  .brand .mark { width:44px; height:44px; border-radius:10px;\n"
    "                 background:linear-gradient(135deg,var(--accent) 0%,var(--accent-2) 100%);\n"
    "                 display:flex; align-items:center; justify-content:center;\n"
    "                 font-family:var(--mono); font-weight:800; font-size:18px; color:var(--bg-0);\n"
    "                 letter-spacing:-0.5px; box-shadow:0 0 24px rgba(78,201,176,0.3); }\n"
    "  .brand h1 { margin:0; font-size:20px; font-weight:600; letter-spacing:0.2px; }\n"
    "  .brand .sub { margin:2px 0 0; font-family:var(--mono); font-size:11px; color:var(--text-dim); letter-spacing:0.5px; }\n"
    "  .fw-ver { color:var(--accent); font-weight:600; }\n"
    "\n"
    "  .status-pill { display:inline-flex; align-items:center; gap:8px; padding:8px 14px;\n"
    "                 border-radius:999px; background:rgba(80,250,123,0.08);\n"
    "                 border:1px solid rgba(80,250,123,0.3);\n"
    "                 font-family:var(--mono); font-size:12px; letter-spacing:1px; color:var(--ok);\n"
    "                 transition:all 0.3s ease; }\n"
    "  .status-pill.warn { background:rgba(255,184,108,0.08); border-color:rgba(255,184,108,0.3); color:var(--warn); }\n"
    "  .status-pill.warn .dot { background:var(--warn); box-shadow:0 0 8px var(--warn); }\n"
    "  .status-pill.err { background:rgba(255,85,119,0.08); border-color:rgba(255,85,119,0.3); color:var(--err); }\n"
    "  .status-pill.err .dot { background:var(--err); box-shadow:0 0 8px var(--err); }\n"
    "  .status-pill .dot { width:8px; height:8px; border-radius:50%; background:var(--ok);\n"
    "                      box-shadow:0 0 8px var(--ok); animation:pulse 2s ease-in-out infinite; }\n"
    "  @keyframes pulse { 0%,100%{opacity:1;transform:scale(1);} 50%{opacity:0.5;transform:scale(0.85);} }\n"
    "\n"
    "  .grid { display:grid; grid-template-columns:repeat(12,1fr); gap:18px; }\n"
    "  .card { background:linear-gradient(180deg,var(--bg-1) 0%,var(--bg-2) 100%);\n"
    "          border:1px solid var(--line-soft); border-radius:14px; padding:18px 20px;\n"
    "          position:relative; overflow:hidden; transition:border-color 0.2s ease; }\n"
    "  .card:hover { border-color:var(--line); }\n"
    "  .card::before { content:\"\"; position:absolute; top:0; left:0; right:0; height:1px;\n"
    "                  background:linear-gradient(90deg,transparent,var(--line),transparent); }\n"
    "  .card-header { display:flex; align-items:center; justify-content:space-between;\n"
    "                 margin-bottom:14px; padding-bottom:10px; border-bottom:1px dashed var(--line-soft); }\n"
    "  .card-header h2 { margin:0; font-size:11px; font-weight:700; letter-spacing:2px;\n"
    "                    text-transform:uppercase; color:var(--text-dim); }\n"
    "  .card-header .badge { font-family:var(--mono); font-size:10px; color:var(--text-mute); letter-spacing:0.5px; }\n"
    "\n"
    "  .col-3{grid-column:span 3;} .col-4{grid-column:span 4;} .col-5{grid-column:span 5;}\n"
    "  .col-6{grid-column:span 6;} .col-7{grid-column:span 7;} .col-8{grid-column:span 8;}\n"
    "  .col-12{grid-column:span 12;}\n"
    "  @media (max-width:960px){ .col-3,.col-4,.col-5,.col-6,.col-7,.col-8{grid-column:span 12;} }\n"
    "\n"
    "  .rows { display:flex; flex-direction:column; gap:2px; }\n"
    "  .row { display:grid; grid-template-columns:28px 1fr auto; align-items:center; gap:12px;\n"
    "         padding:9px 4px; border-bottom:1px solid transparent; transition:background 0.15s ease; }\n"
    "  .row:hover { background:rgba(255,255,255,0.015); }\n"
    "  .row + .row { border-top:1px solid var(--line-soft); }\n"
    "  .row .icon { font-family:var(--emoji); font-size:18px; line-height:1;\n"
    "               text-align:center; width:28px; display:inline-flex;\n"
    "               align-items:center; justify-content:center; filter:saturate(1.1); }\n"
    "  .row .label { font-size:13px; color:var(--text); font-weight:500; letter-spacing:0.1px; }\n"
    "  .row .label .hint { display:block; font-family:var(--mono); font-size:10px;\n"
    "                      color:var(--text-mute); font-weight:400; margin-top:2px; letter-spacing:0.3px; }\n"
    "  .row .value { font-family:var(--mono); font-size:12.5px; color:var(--text);\n"
    "                text-align:right; font-variant-numeric:tabular-nums;\n"
    "                transition:color 0.3s ease; }\n"
    "  .row .value.dim{color:var(--text-dim);} .row .value.ok{color:var(--ok);}\n"
    "  .row .value.warn{color:var(--warn);} .row .value.err{color:var(--err);}\n"
    "  .row .value.info{color:var(--info);} .row .value.accent{color:var(--accent);}\n"
    "  .row .value.purple{color:var(--purple);}\n"
    "  .row .value.hostname{max-width:220px;min-width:0;overflow-wrap:anywhere;line-height:1.25;}\n"
    "\n"
    "  .chip { display:inline-block; padding:2px 8px; border-radius:4px;\n"
    "          font-family:var(--mono); font-size:11px; letter-spacing:0.5px;\n"
    "          border:1px solid currentColor; background:rgba(255,255,255,0.02); }\n"
    "  .chip.ok{color:var(--ok); background:rgba(80,250,123,0.08);}\n"
    "  .chip.warn{color:var(--warn); background:rgba(255,184,108,0.08);}\n"
    "  .chip.err{color:var(--err); background:rgba(255,85,119,0.08);}\n"
    "  .chip.info{color:var(--info); background:rgba(139,233,253,0.08);}\n"
    "\n"
    "  .hero { grid-column:span 12; display:grid; grid-template-columns:repeat(4,1fr); gap:18px; }\n"
    "  @media (max-width:960px){ .hero{grid-template-columns:repeat(2,1fr);} }\n"
    "  .metric { background:linear-gradient(180deg,var(--bg-1) 0%,var(--bg-2) 100%);\n"
    "            border:1px solid var(--line-soft); border-radius:14px; padding:18px 20px;\n"
    "            position:relative; overflow:hidden; transition:border-color 0.3s ease; }\n"
    "  .metric .metric-head { display:flex; align-items:center; gap:10px; margin-bottom:12px; }\n"
    "  .metric .metric-head .icon { font-family:var(--emoji); font-size:18px; }\n"
    "  .metric .metric-head .label { font-size:10px; letter-spacing:2px; text-transform:uppercase;\n"
    "                                color:var(--text-dim); font-weight:700; }\n"
    "  .metric .big { font-family:var(--mono); font-size:26px; font-weight:700;\n"
    "                 color:var(--text); letter-spacing:-0.5px; line-height:1.1;\n"
    "                 transition:color 0.3s ease; }\n"
    "  .metric .big .unit { font-size:14px; color:var(--text-dim); }\n"
    "  .metric .sub { margin-top:6px; font-family:var(--mono); font-size:11px;\n"
    "                 color:var(--text-mute); letter-spacing:0.3px; }\n"
    "  .metric.locked { border-color:rgba(80,250,123,0.25); }\n"
    "  .metric.locked .big { color:var(--ok); }\n"
    "  .metric.holdover { border-color:rgba(255,184,108,0.25); }\n"
    "  .metric.holdover .big { color:var(--warn); }\n"
    "  .metric.fault, .metric.no-link { border-color:rgba(255,85,119,0.25); }\n"
    "  .metric.fault .big, .metric.no-link .big { color:var(--err); }\n"
    "\n"
    "  .tasks { width:100%; border-collapse:collapse; font-size:12px; font-family:var(--mono); }\n"
    "  .tasks thead th { text-align:left; padding:8px 10px; border-bottom:1px solid var(--line);\n"
    "                    color:var(--text-dim); font-weight:600; font-size:10px;\n"
    "                    letter-spacing:1.5px; text-transform:uppercase; }\n"
    "  .tasks tbody td { padding:7px 10px; border-bottom:1px solid var(--line-soft);\n"
    "                    color:var(--text); font-variant-numeric:tabular-nums; }\n"
    "  .tasks tbody tr:hover { background:rgba(255,255,255,0.02); }\n"
    "  .tasks .tname { display:inline-flex; align-items:center; gap:8px; }\n"
    "  .tasks .tname .icon { font-family:var(--emoji); font-size:14px; }\n"
    "  .prio { display:inline-block; min-width:22px; text-align:center; padding:1px 6px;\n"
    "          border-radius:4px; font-size:11px; font-weight:700; }\n"
    "  .prio.p7{background:rgba(255,85,119,0.15); color:var(--err);}\n"
    "  .prio.p6{background:rgba(255,184,108,0.15); color:var(--warn);}\n"
    "  .prio.p5{background:rgba(241,196,15,0.15); color:var(--gold);}\n"
    "  .prio.p2{background:rgba(139,233,253,0.15); color:var(--info);}\n"
    "  .prio.p1{background:rgba(122,162,247,0.15); color:var(--accent-2);}\n"
    "  .bar { display:inline-block; width:60px; height:5px; background:var(--bg-3);\n"
    "         border-radius:99px; overflow:hidden; vertical-align:middle; margin-right:8px; }\n"
    "  .bar > i { display:block; height:100%;\n"
    "             background:linear-gradient(90deg,var(--accent),var(--accent-2));\n"
    "             border-radius:99px; transition:width 0.5s ease; }\n"
    "\n"
    "  footer { margin-top:32px; padding-top:16px; border-top:1px solid var(--line-soft);\n"
    "           text-align:center; font-family:var(--mono); font-size:10.5px;\n"
    "           color:var(--text-mute); letter-spacing:1px; }\n"
    "  footer a { color:var(--accent); text-decoration:none; border-bottom:1px dashed transparent;\n"
    "             transition:border-color 0.2s ease; }\n"
    "  footer a:hover { border-bottom-color:var(--accent); }\n"
    "  footer .live { color:var(--accent); margin-left:6px; }\n"
    "  footer .sep { margin:0 8px; color:var(--text-mute); opacity:0.5; }\n"
    "\n"
    "  /* OTA link button in header */\n"
    "  .ota-link {\n"
    "    display:inline-flex; align-items:center; gap:8px;\n"
    "    padding:8px 14px; border-radius:999px;\n"
    "    background:rgba(122,162,247,0.08);\n"
    "    border:1px solid rgba(122,162,247,0.3);\n"
    "    font-family:var(--mono); font-size:12px; letter-spacing:1px;\n"
    "    color:var(--accent-2); text-decoration:none;\n"
    "    transition:all 0.2s ease;\n"
    "    margin-right:8px;\n"
    "  }\n"
    "  .ota-link:hover {\n"
    "    background:rgba(122,162,247,0.15);\n"
    "    border-color:var(--accent-2);\n"
    "    transform:translateY(-1px);\n"
    "  }\n"
    "  .ota-link .icon { font-family:var(--emoji); font-size:14px; }\n"
    "\n"
    "  .header-actions { display:flex; align-items:center; gap:0; flex-wrap:wrap; }\n"
    "\n"
    "  /* fade flash on update */\n"
    "  .flash { animation:flash 0.6s ease; }\n"
    "  @keyframes flash { 0%{background:rgba(78,201,176,0.1);} 100%{background:transparent;} }\n"
    "\n"
    "  /* Load / Soak monitor panel */\n"
    "  .btn-mon { display:inline-flex; align-items:center; gap:8px; cursor:pointer;\n"
    "             padding:7px 14px; border-radius:999px; font-family:var(--mono);\n"
    "             font-size:12px; letter-spacing:1px; user-select:none;\n"
    "             background:rgba(80,250,123,0.08); border:1px solid rgba(80,250,123,0.35);\n"
    "             color:var(--ok); transition:all 0.2s ease; }\n"
    "  .btn-mon:hover { background:rgba(80,250,123,0.16); transform:translateY(-1px); }\n"
    "  .btn-mon.on { background:rgba(255,85,119,0.08); border-color:rgba(255,85,119,0.35); color:var(--err); }\n"
    "  .btn-mon.on:hover { background:rgba(255,85,119,0.16); }\n"
    "  .btn-mon .icon { font-family:var(--emoji); font-size:13px; }\n"
    "  .mon-stats { display:grid; grid-template-columns:repeat(4,1fr); gap:14px; margin-bottom:16px; }\n"
    "  @media (max-width:960px){ .mon-stats{grid-template-columns:repeat(2,1fr);} }\n"
    "  .mon-spark { display:grid; grid-template-columns:1fr 1fr; gap:14px; margin-bottom:6px; }\n"
    "  @media (max-width:960px){ .mon-spark{grid-template-columns:1fr;} }\n"
    "  .spark-box { background:var(--bg-0); border:1px solid var(--line-soft); border-radius:10px; padding:10px 12px; }\n"
    "  .spark-box .sh { display:flex; justify-content:space-between; align-items:baseline; margin-bottom:6px; }\n"
    "  .spark-box .sh .t { font-size:10px; letter-spacing:1.5px; text-transform:uppercase; color:var(--text-dim); font-weight:700; }\n"
    "  .spark-box .sh .v { font-family:var(--mono); font-size:12px; color:var(--text); font-variant-numeric:tabular-nums; }\n"
    "  .spark-box canvas { display:block; width:100%; height:48px; }\n"
    "  .mon-idle { color:var(--text-mute); font-family:var(--mono); font-size:12px;\n"
    "              text-align:center; padding:22px 12px; letter-spacing:0.3px; line-height:1.6; }\n"
    "  .mon-check { display:inline-flex; align-items:center; gap:6px; cursor:pointer;\n"
    "              font-family:var(--mono); font-size:11px; letter-spacing:0.5px;\n"
    "              color:var(--text-dim); user-select:none; }\n"
    "  .mon-check:hover { color:var(--text); }\n"
    "  .mon-check input { accent-color:var(--accent); width:13px; height:13px; cursor:pointer; margin:0; }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"container\">\n"
    "\n"
    "  <header>\n"
    "    <div class=\"brand\">\n"
    "      <div class=\"mark\">P4</div>\n"
    "      <div>\n"
    "        <h1>PTP Master &mdash; ESP32-P4 Grandmaster</h1>\n"
    "        <div class=\"sub\">IEEE 1588-2008 &middot; L2/Ethernet Transport &middot; Domain 0\n"
    "          &middot; <span class=\"fw-ver\" id=\"hdr_fw\">fw &mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div class=\"header-actions\">\n"
    "      <a class=\"ota-link\" href=\"/ota\" title=\"Firmware update\">\n"
    "        <span class=\"icon\">&#x1F680;</span><span>OTA UPDATE</span>\n"
    "      </a>\n"
    "      <div class=\"status-pill\" id=\"hdrStatus\">\n"
    "        <span class=\"dot\"></span><span id=\"hdrStatusText\">CONNECTING&hellip;</span>\n"
    "      </div>\n"
    "    </div>\n"
    "  </header>\n"
    "\n"
    "  <div class=\"grid\">\n"
    "\n"
    "    <!-- HERO METRICS -->\n"
    "    <div class=\"hero\">\n"
    "      <div class=\"metric\" id=\"m_state\">\n"
    "        <div class=\"metric-head\"><span class=\"icon\">&#x1F512;</span><span class=\"label\">Sync State</span></div>\n"
    "        <div class=\"big\" id=\"v_state\">&mdash;</div>\n"
    "        <div class=\"sub\" id=\"v_state_sub\">awaiting data</div>\n"
    "      </div>\n"
    "      <div class=\"metric\">\n"
    "        <div class=\"metric-head\"><span class=\"icon\">&#x1F3AF;</span><span class=\"label\">Offset</span></div>\n"
    "        <div class=\"big\" id=\"v_offset\">&mdash;</div>\n"
    "        <div class=\"sub\" id=\"v_offset_sub\">median window: 5</div>\n"
    "      </div>\n"
    "      <div class=\"metric\">\n"
    "        <div class=\"metric-head\"><span class=\"icon\">&#x269B;&#xFE0F;</span><span class=\"label\">Frequency Adj.</span></div>\n"
    "        <div class=\"big\" id=\"v_freq\">&mdash;</div>\n"
    "        <div class=\"sub\" id=\"v_freq_sub\">Kp=0.4 &middot; Ki=0.3</div>\n"
    "      </div>\n"
    "      <div class=\"metric\">\n"
    "        <div class=\"metric-head\"><span class=\"icon\">&#x1F6F0;&#xFE0F;</span><span class=\"label\">GNSS / PPS</span></div>\n"
    "        <div class=\"big\" id=\"v_gnss\">&mdash;</div>\n"
    "        <div class=\"sub\" id=\"v_gnss_sub\">&mdash;</div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- DEVICE -->\n"
    "    <div class=\"card col-4\">\n"
    "      <div class=\"card-header\"><h2>Device</h2><span class=\"badge\" id=\"b_dev\">ESP32-P4</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F9E0;</span>\n"
    "          <span class=\"label\">Chip<span class=\"hint\">Dual RISC-V HP core</span></span>\n"
    "          <span class=\"value\" id=\"v_chip\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x26A1;</span>\n"
    "          <span class=\"label\">CPU Frequency</span>\n"
    "          <span class=\"value accent\" id=\"v_cpufreq\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4E6;</span>\n"
    "          <span class=\"label\">Project<span class=\"hint\" id=\"v_appver\">app version &mdash;</span></span>\n"
    "          <span class=\"value\" id=\"v_proj\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4DD;</span>\n"
    "          <span class=\"label\">ESP-IDF</span>\n"
    "          <span class=\"value\" id=\"v_idf\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F6E0;&#xFE0F;</span>\n"
    "          <span class=\"label\">Compile time</span>\n"
    "          <span class=\"value dim\" id=\"v_compile\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F511;</span>\n"
    "          <span class=\"label\">ELF SHA-256</span>\n"
    "          <span class=\"value dim\" id=\"v_sha\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4BE;</span>\n"
    "          <span class=\"label\">Flash</span>\n"
    "          <span class=\"value\" id=\"v_flash\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F551;</span>\n"
    "          <span class=\"label\">Uptime</span>\n"
    "          <span class=\"value ok\" id=\"v_uptime\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- MEMORY -->\n"
    "    <div class=\"card col-4\">\n"
    "      <div class=\"card-header\"><h2>Memory</h2><span class=\"badge\">internal heap</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F49A;</span>\n"
    "          <span class=\"label\">Free heap<span class=\"hint\">MALLOC_CAP_INTERNAL</span></span>\n"
    "          <span class=\"value ok\" id=\"v_heap_free\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4C9;</span>\n"
    "          <span class=\"label\">Min ever free<span class=\"hint\">low-water mark since boot</span></span>\n"
    "          <span class=\"value warn\" id=\"v_heap_min\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F9F1;</span>\n"
    "          <span class=\"label\">Largest free block</span>\n"
    "          <span class=\"value\" id=\"v_heap_lfb\">&mdash;</span></div>\n"
    "        <div class=\"row\" title=\"Internal SRAM that can be accessed by the ESP32-P4 retention-DMA engine. ESP-IDF may also use it as ordinary heap memory.\"><span class=\"icon\">&#x1F3DB;&#xFE0F;</span>\n"
    "          <span class=\"label\">Retention-capable RAM<span class=\"hint\">MALLOC_CAP_RETENTION &middot; free / total</span></span>\n"
    "          <span class=\"value dim\" id=\"v_retent\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4D0;</span>\n"
    "          <span class=\"label\">RAM regions</span>\n"
    "          <span class=\"value dim\" id=\"v_ram\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F50B;</span>\n"
    "          <span class=\"label\">RTC RAM</span>\n"
    "          <span class=\"value dim\" id=\"v_rtcram\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4BD;</span>\n"
    "          <span class=\"label\">TCM</span>\n"
    "          <span class=\"value dim\" id=\"v_tcm\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x267B;&#xFE0F;</span>\n"
    "          <span class=\"label\">Leak delta<span class=\"hint\">since baseline</span></span>\n"
    "          <span class=\"value ok\" id=\"v_leak\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- NETWORK -->\n"
    "    <div class=\"card col-4\">\n"
    "      <div class=\"card-header\"><h2>Network</h2><span class=\"badge\">EMAC &middot; L2TAP</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F50C;</span>\n"
    "          <span class=\"label\">Link status</span>\n"
    "          <span class=\"value\" id=\"v_link\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F3E0;</span>\n"
    "          <span class=\"label\">Hostname<span class=\"hint\">DHCP / DNS / mDNS identity</span></span>\n"
    "          <span class=\"value accent hostname\" id=\"v_hostname\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F310;</span>\n"
    "          <span class=\"label\">IP address<span class=\"hint\" id=\"v_ip_hint\">&mdash;</span></span>\n"
    "          <span class=\"value info\" id=\"v_ip\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F3F7;&#xFE0F;</span>\n"
    "          <span class=\"label\">MAC address</span>\n"
    "          <span class=\"value dim\" id=\"v_mac\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4E1;</span>\n"
    "          <span class=\"label\">L2TAP<span class=\"hint\">EtherType 0x88F7</span></span>\n"
    "          <span class=\"value\" id=\"v_l2tap\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4EC;</span>\n"
    "          <span class=\"label\">PTP multicast filter</span>\n"
    "          <span class=\"value dim\" id=\"v_mcast\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F501;</span>\n"
    "          <span class=\"label\">EMAC restarts<span class=\"hint\">RX descriptor recovery</span></span>\n"
    "          <span class=\"value\" id=\"v_emac\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F6AB;</span>\n"
    "          <span class=\"label\">Promiscuous</span>\n"
    "          <span class=\"value dim\" id=\"v_promisc\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F6E1;&#xFE0F;</span>\n"
    "          <span class=\"label\">Watchdog<span class=\"hint\">heap pressure recovery</span></span>\n"
    "          <span class=\"value ok\" id=\"v_wdt\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- PTP / TIMING -->\n"
    "    <div class=\"card col-6\">\n"
    "      <div class=\"card-header\"><h2>PTP &middot; Timing</h2><span class=\"badge\">grandmaster &middot; 2-step</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F451;</span>\n"
    "          <span class=\"label\">Role<span class=\"hint\">BMCA result</span></span>\n"
    "          <span class=\"value accent\" id=\"v_role\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F194;</span>\n"
    "          <span class=\"label\">Clock ID</span>\n"
    "          <span class=\"value dim\" id=\"v_clockid\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F551;</span>\n"
    "          <span class=\"label\">UTC time<span class=\"hint\">from GNSS &middot; gmtime_r</span></span>\n"
    "          <span class=\"value info\" id=\"v_utc\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x23F3;</span>\n"
    "          <span class=\"label\">TAI &minus; UTC offset</span>\n"
    "          <span class=\"value\" id=\"v_tai\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4E4;</span>\n"
    "          <span class=\"label\">Sync interval</span>\n"
    "          <span class=\"value dim\" id=\"v_sync_int\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4E2;</span>\n"
    "          <span class=\"label\">Announce interval</span>\n"
    "          <span class=\"value dim\" id=\"v_ann_int\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F522;</span>\n"
    "          <span class=\"label\">Sync seq &middot; Announce seq</span>\n"
    "          <span class=\"value\" id=\"v_seq\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4CD;</span>\n"
    "          <span class=\"label\">Path delay<span class=\"hint\">slave-side measurement</span></span>\n"
    "          <span class=\"value dim\" id=\"v_path\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F465;</span>\n"
    "          <span class=\"label\">Active slaves<span class=\"hint\">tracked &middot; 30s window</span></span>\n"
    "          <span class=\"value purple\" id=\"v_slaves\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- SERVO -->\n"
    "    <div class=\"card col-6\">\n"
    "      <div class=\"card-header\"><h2>Servo &middot; Discipline</h2><span class=\"badge\">PI &middot; linreg window 16</span></div>\n"
    "      <div class=\"rows\">\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F7E2;</span>\n"
    "          <span class=\"label\">Servo state</span>\n"
    "          <span class=\"value ok\" id=\"v_servo\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4CA;</span>\n"
    "          <span class=\"label\">Integrator</span>\n"
    "          <span class=\"value\" id=\"v_integ\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4C8;</span>\n"
    "          <span class=\"label\">Lock quality<span class=\"hint\">good samples / 64</span></span>\n"
    "          <span class=\"value ok\" id=\"v_lockq\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x231A;</span>\n"
    "          <span class=\"label\">PPS edges captured</span>\n"
    "          <span class=\"value\" id=\"v_pps\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F6AB;</span>\n"
    "          <span class=\"label\">Sample rejects<span class=\"hint\">offset &gt;100&micro;s from avg &middot; lifetime</span></span>\n"
    "          <span class=\"value ok\" id=\"v_reject\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F50D;</span>\n"
    "          <span class=\"label\">PHC residual<span class=\"hint\">measured steady-state</span></span>\n"
    "          <span class=\"value dim\" id=\"v_phc\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F198;</span>\n"
    "          <span class=\"label\">Holdover timeout</span>\n"
    "          <span class=\"value dim\" id=\"v_holdto\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x2705;</span>\n"
    "          <span class=\"label\">Post-holdover settled</span>\n"
    "          <span class=\"value\" id=\"v_settled\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F6F0;&#xFE0F;</span>\n"
    "          <span class=\"label\">GNSS last update</span>\n"
    "          <span class=\"value\" id=\"v_gnssage\">&mdash;</span></div>\n"
    "        <div class=\"row\"><span class=\"icon\">&#x1F4A1;</span>\n"
    "          <span class=\"label\">PPS LED<span class=\"hint\">GPIO 3 &middot; 50 ms pulse</span></span>\n"
    "          <span class=\"value info\" id=\"v_ppsled\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- TASKS -->\n"
    "    <div class=\"card col-12\">\n"
    "      <div class=\"card-header\"><h2>FreeRTOS Tasks</h2><span class=\"badge\" id=\"b_tasks\">&mdash; tasks</span></div>\n"
    "      <table class=\"tasks\">\n"
    "        <thead>\n"
    "          <tr>\n"
    "            <th style=\"width:24%\">Task</th>\n"
    "            <th style=\"width:10%\">Priority</th>\n"
    "            <th style=\"width:14%\">Stack</th>\n"
    "            <th style=\"width:18%\">High-water mark</th>\n"
    "            <th style=\"width:10%\">Core</th>\n"
    "            <th>Role</th>\n"
    "          </tr>\n"
    "        </thead>\n"
    "        <tbody id=\"tasksBody\">\n"
    "          <tr><td colspan=\"6\" style=\"text-align:center; color:var(--text-mute); padding:20px;\">awaiting data&hellip;</td></tr>\n"
    "        </tbody>\n"
    "      </table>\n"
    "    </div>\n"
    "\n"
    "    <!-- LOAD / SOAK MONITOR (opt-in; polls /api/health) -->\n"
    "    <div class=\"card col-12\">\n"
    "      <div class=\"card-header\">\n"
    "        <h2>Load / Soak Monitor</h2>\n"
    "        <div style=\"display:flex; align-items:center; gap:12px; flex-wrap:wrap;\">\n"
    "          <label class=\"mon-check\" title=\"While monitoring, stop the 5s /api/status poll so the page requests only /api/health\"><input type=\"checkbox\" id=\"monPauseStatus\"> pause status poll</label>\n"
    "          <span class=\"badge\" id=\"monBadge\">stopped &middot; polls /api/health</span>\n"
    "          <span class=\"btn-mon\" id=\"monToggle\"><span class=\"icon\">&#x25B6;&#xFE0F;</span><span id=\"monToggleText\">Start monitoring</span></span>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"monIdle\" class=\"mon-idle\">Monitoring is off &mdash; the device is <strong>not</strong> polled until you opt in.<br>Click &ldquo;Start monitoring&rdquo; to begin fetching <code>/api/health</code> every <span id=\"monIdleMs\">1000</span>&nbsp;ms.</div>\n"
    "      <div id=\"monBody\" style=\"display:none;\">\n"
    "        <div class=\"mon-stats\">\n"
    "          <div class=\"metric\"><div class=\"metric-head\"><span class=\"icon\">&#x1F4C8;</span><span class=\"label\">Sync Jitter p2p</span></div><div class=\"big\" id=\"h_jit\">&mdash;</div><div class=\"sub\" id=\"h_jit_sub\">peak-to-peak &middot; window</div></div>\n"
    "          <div class=\"metric\"><div class=\"metric-head\"><span class=\"icon\">&#x1F525;</span><span class=\"label\">RX Task CPU</span></div><div class=\"big\" id=\"h_rxcpu\">&mdash;</div><div class=\"sub\" id=\"h_rxcpu_sub\">ptp_rx share</div></div>\n"
    "          <div class=\"metric\"><div class=\"metric-head\"><span class=\"icon\">&#x1F4C9;</span><span class=\"label\">Heap Min</span></div><div class=\"big\" id=\"h_heapmin\">&mdash;</div><div class=\"sub\" id=\"h_heapmin_sub\">low-water since boot</div></div>\n"
    "          <div class=\"metric\"><div class=\"metric-head\"><span class=\"icon\">&#x1F4D0;</span><span class=\"label\">RX Stack HWM</span></div><div class=\"big\" id=\"h_rxstack\">&mdash;</div><div class=\"sub\" id=\"h_rxstack_sub\">headroom remaining</div></div>\n"
    "        </div>\n"
    "        <div class=\"mon-spark\">\n"
    "          <div class=\"spark-box\"><div class=\"sh\"><span class=\"t\">Sync jitter p2p (&#xB5;s)</span><span class=\"v\" id=\"sp_jit_v\">&mdash;</span></div><canvas id=\"sp_jit\" width=\"560\" height=\"48\"></canvas></div>\n"
    "          <div class=\"spark-box\"><div class=\"sh\"><span class=\"t\">Heap min (KB)</span><span class=\"v\" id=\"sp_heap_v\">&mdash;</span></div><canvas id=\"sp_heap\" width=\"560\" height=\"48\"></canvas></div>\n"
    "        </div>\n"
    "        <table class=\"tasks\" style=\"margin-top:6px;\">\n"
    "          <thead><tr><th style=\"width:30%\">Task</th><th style=\"width:14%\">Priority</th><th style=\"width:30%\">CPU (since last poll)</th><th>Stack high-water</th></tr></thead>\n"
    "          <tbody id=\"monTasksBody\"><tr><td colspan=\"4\" style=\"text-align:center;color:var(--text-mute);padding:16px;\">awaiting first poll&hellip;</td></tr></tbody>\n"
    "        </table>\n"
    "        <div style=\"margin-top:10px; font-family:var(--mono); font-size:10.5px; color:var(--text-mute); letter-spacing:0.5px;\">Last health poll <span id=\"monLast\">&mdash;</span> &middot; interval <span id=\"monInt\">&mdash;</span>&nbsp;ms &middot; <span id=\"monRt\">&mdash;</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "  </div>\n"
    "\n"
    "  <footer>\n"
    "    Last refresh <span class=\"live\" id=\"lastRefresh\">&mdash;</span>\n"
    "    <span class=\"sep\">&middot;</span> auto-refresh every 5000 ms\n"
    "    <span class=\"sep\">&middot;</span>\n"
    "    <a href=\"https://github.com/Montecri/GNSSTimeServer\" target=\"_blank\" rel=\"noopener\">github.com/Montecri/GNSSTimeServer</a>\n"
    "  </footer>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "\"use strict\";\n"
    "\n"
    "/* Health-monitor poll interval (ms), injected from the C #define\n"
    "   HEALTH_POLL_INTERVAL_MS so firmware and page never disagree. */\n"
    "const HEALTH_POLL_MS = " SP_STR(HEALTH_POLL_INTERVAL_MS) ";\n"
    "\n"
    "/* ─── Icon map for known FreeRTOS task names ─── */\n"
    "const TASK_META = {\n"
    "  \"ptp_rx\":   { icon:\"\\u{1F4E5}\", role:\"L2TAP RX, hw timestamps, dispatch\" },\n"
    "  \"ptp_tx\":   { icon:\"\\u{1F4E4}\", role:\"Sync / Announce\" },\n"
    "  \"dresp\":    { icon:\"\\u{1F4EC}\", role:\"Delay_Resp worker\" },\n"
    "  \"gnss\":      { icon:\"\\u{1F6F0}\\uFE0F\", role:\"NMEA parser \\u00B7 UART1 @ 9600\" },\n"
    "  \"servo\":    { icon:\"\\u2699\\uFE0F\", role:\"PI servo, freq/step discipline\" },\n"
    "  \"pps_task\": { icon:\"\\u{1F551}\", role:\"1-PPS edge handler, PHC capture\" },\n"
    "  \"pps_led\":  { icon:\"\\u{1F4A1}\", role:\"PPS visual indicator (GPIO 3)\" },\n"
    "  \"led\":      { icon:\"\\u{1F506}\", role:\"Status LED state machine\" },\n"
    "  \"display\":  { icon:\"\\u{1F4FA}\", role:\"SH1106 OLED \\u00B7 3 screens\" },\n"
    "  \"btn\":      { icon:\"\\u{1F518}\", role:\"Display button \\u00B7 GPIO 1\" },\n"
    "  \"dhcp_fb\":  { icon:\"\\u{1F310}\", role:\"DHCP fallback \\u00B7 8 s timeout\" },\n"
    "  \"heap_mon\": { icon:\"\\u{1F4CA}\", role:\"Heap watchdog \\u00B7 60 s interval\" },\n"
    "  \"wdt\":      { icon:\"\\u{1F415}\", role:\"Watchdog \\u00B7 EMAC restart logic\" },\n"
    "  \"main\":     { icon:\"\\u{1F3E1}\", role:\"Init & supervision (idle)\" }\n"
    "};\n"
    "\n"
    "/* ─── Helpers ─── */\n"
    "const $ = (id) => document.getElementById(id);\n"
    "const fmtKB = (b) => (b/1024).toFixed(0) + \" KB\";\n"
    "\n"
    "function setText(id, val) {\n"
    "  const el = $(id);\n"
    "  if (!el) return;\n"
    "  if (el.textContent !== String(val)) {\n"
    "    el.textContent = val;\n"
    "  }\n"
    "}\n"
    "\n"
    "function setClass(id, cls) {\n"
    "  const el = $(id);\n"
    "  if (el) el.className = cls;\n"
    "}\n"
    "\n"
    "function formatUptime(s) {\n"
    "  if (typeof s !== \"number\" || s < 0) return \"\\u2014\";\n"
    "  const d = Math.floor(s / 86400);\n"
    "  const h = Math.floor((s % 86400) / 3600);\n"
    "  const m = Math.floor((s % 3600) / 60);\n"
    "  const sec = s % 60;\n"
    "  const pad = (n) => String(n).padStart(2, \"0\");\n"
    "  if (d > 0) return d + \"d \" + pad(h) + \"h\" + pad(m) + \"m\";\n"
    "  return pad(h) + \":\" + pad(m) + \":\" + pad(sec);\n"
    "}\n"
    "\n"
    "function prioClass(p) {\n"
    "  if (p >= 7) return \"prio p7\";\n"
    "  if (p === 6) return \"prio p6\";\n"
    "  if (p === 5) return \"prio p5\";\n"
    "  if (p === 2) return \"prio p2\";\n"
    "  return \"prio p1\";\n"
    "}\n"
    "\n"
    "/* ─── Main render ─── */\n"
    "function render(d) {\n"
    "  /* Header status pill */\n"
    "  const pill = $(\"hdrStatus\");\n"
    "  const stateUp = (d.servo_state || \"\").toUpperCase();\n"
    "  pill.className = \"status-pill\";\n"
    "  let pillText = \"SERVO \" + (stateUp || \"?\");\n"
    "  if (stateUp === \"LOCKED\") pill.className = \"status-pill\";\n"
    "  else if (stateUp === \"HOLDOVER\" || stateUp === \"ACQUIRING\") pill.className = \"status-pill warn\";\n"
    "  else pill.className = \"status-pill err\";\n"
    "  setText(\"hdrStatusText\", pillText);\n"
    "\n"
    "  /* Hero — Sync state */\n"
    "  const mState = $(\"m_state\");\n"
    "  mState.className = \"metric\";\n"
    "  if (stateUp === \"LOCKED\") mState.classList.add(\"locked\");\n"
    "  else if (stateUp === \"HOLDOVER\") mState.classList.add(\"holdover\");\n"
    "  else if (stateUp === \"FAULT\") mState.classList.add(\"fault\");\n"
    "  else if (stateUp === \"NO_LINK\" || stateUp === \"NO LINK\") mState.classList.add(\"no-link\");\n"
    "  setText(\"v_state\", stateUp || \"\\u2014\");\n"
    "  setText(\"v_state_sub\", d.locked_for ? (\"held \" + d.locked_for) : \"median window: 5\");\n"
    "\n"
    "  /* Hero — Offset */\n"
    "  if (typeof d.offset_ns === \"number\" && (stateUp === \"LOCKED\" || stateUp === \"HOLDOVER\")) {\n"
    "    const sign = d.offset_ns >= 0 ? \"+\" : \"\";\n"
    "    $(\"v_offset\").innerHTML = sign + d.offset_ns + ' <span class=\"unit\">ns</span>';\n"
    "  } else {\n"
    "    setText(\"v_offset\", \"\\u2014\");\n"
    "  }\n"
    "\n"
    "  /* Hero — Frequency */\n"
    "  if (typeof d.freq_ppb === \"number\") {\n"
    "    const sign = d.freq_ppb >= 0 ? \"+\" : \"\";\n"
    "    $(\"v_freq\").innerHTML = sign + d.freq_ppb.toFixed(1) + ' <span class=\"unit\">ppb</span>';\n"
    "  } else {\n"
    "    setText(\"v_freq\", \"\\u2014\");\n"
    "  }\n"
    "\n"
    "  /* Hero — GNSS */\n"
    "  setText(\"v_gnss\", d.gnss_fix ? \"FIX OK\" : \"NO FIX\");\n"
    "  $(\"v_gnss\").style.color = d.gnss_fix ? \"var(--ok)\" : \"var(--err)\";\n"
    "  setText(\"v_gnss_sub\", \"PPS count: \" + (d.pps_count != null ? d.pps_count.toLocaleString() : \"\\u2014\"));\n"
    "\n"
    "  /* Device */\n"
    "  setText(\"v_chip\", (d.chip || \"ESP32-P4\") + \" rev \" + (d.chip_rev || \"v1.0\"));\n"
    "  setText(\"b_dev\", (d.chip || \"ESP32-P4\") + \" \\u00B7 rev \" + (d.chip_rev || \"v1.0\"));\n"
    "  setText(\"v_cpufreq\", (d.cpu_mhz || 0) + \" MHz\");\n"
    "  setText(\"v_proj\", d.project || \"\\u2014\");\n"
    "  setText(\"v_appver\", \"app version \" + (d.app_version || \"\\u2014\"));\n"
    "  setText(\"hdr_fw\", \"fw \" + (d.app_version || \"\\u2014\"));\n"
    "  setText(\"v_idf\", d.idf_version || \"\\u2014\");\n"
    "  setText(\"v_compile\", d.compile_time || \"\\u2014\");\n"
    "  setText(\"v_sha\", (d.elf_sha || \"\").substring(0,9) + \"\\u2026\");\n"
    "  setText(\"v_flash\", (d.flash_mb || 16) + \" MB \\u00B7 \" + (d.flash_mode || \"DIO\") + \" \\u00B7 \" + (d.flash_mhz || 80) + \" MHz\");\n"
    "  setText(\"v_uptime\", formatUptime(d.uptime_s || 0));\n"
    "\n"
    "  /* Memory */\n"
    "  setText(\"v_heap_free\", fmtKB(d.heap_free || 0));\n"
    "  setText(\"v_heap_min\",  fmtKB(d.heap_min  || 0));\n"
    "  setText(\"v_heap_lfb\",  fmtKB(d.heap_lfb  || 0));\n"
    "  const retentTotal = d.retent_total != null ? d.retent_total : ((d.retent_kb || 0) * 1024);\n"
    "  const retentFree  = d.retent_free  != null ? d.retent_free  : retentTotal;\n"
    "  setText(\"v_retent\", fmtKB(retentFree) + \" free / \" + fmtKB(retentTotal));\n"
    "  setText(\"v_ram\",       (d.ram1_kb || 384) + \" + \" + (d.ram2_kb || 18) + \" KiB\");\n"
    "  setText(\"v_rtcram\",    (d.rtc_kb || 31) + \" KiB\");\n"
    "  setText(\"v_tcm\",       (d.tcm_kb || 7) + \" KiB\");\n"
    "  if (typeof d.heap_leak === \"number\") {\n"
    "    const lv = $(\"v_leak\");\n"
    "    const sign = d.heap_leak >= 0 ? \"+\" : \"\";\n"
    "    setText(\"v_leak\", sign + d.heap_leak + \" B\");\n"
    "    lv.className = \"value \" + (Math.abs(d.heap_leak) > 1024 ? \"warn\" : \"ok\");\n"
    "  }\n"
    "\n"
    "  /* Network */\n"
    "  const linkUp = !!d.link_up;\n"
    "  $(\"v_link\").innerHTML = linkUp ? '<span class=\"chip ok\">UP</span>' : '<span class=\"chip err\">DOWN</span>';\n"
    "  setText(\"v_hostname\", d.hostname || \"\\u2014\");\n"
    "  if (d.hostname) document.title = d.hostname + \" \\u2014 PTP Master\";\n"
    "  setText(\"v_ip\", d.ip || \"(no IP)\");\n"
    "  setText(\"v_ip_hint\", d.ip_source ? d.ip_source : \"DHCP/static\");\n"
    "  setText(\"v_mac\", d.mac || \"\\u2014\");\n"
    "  $(\"v_l2tap\").innerHTML = d.l2tap_ready ? '<span class=\"chip ok\">READY</span>' : '<span class=\"chip err\">NOT READY</span>';\n"
    "  setText(\"v_mcast\", \"01:1B:19:00:00:00\");\n"
    "  const emacV = $(\"v_emac\");\n"
    "  setText(\"v_emac\", d.emac_restarts != null ? d.emac_restarts : \"\\u2014\");\n"
    "  emacV.className = \"value \" + ((d.emac_restarts || 0) === 0 ? \"ok\" : (d.emac_restarts > 5 ? \"err\" : \"warn\"));\n"
    "  setText(\"v_promisc\", d.promiscuous ? \"enabled\" : \"disabled\");\n"
    "  setText(\"v_wdt\", d.wdt_healthy ? \"healthy\" : \"alerting\");\n"
    "  $(\"v_wdt\").className = \"value \" + (d.wdt_healthy ? \"ok\" : \"err\");\n"
    "\n"
    "  /* PTP / timing */\n"
    "  setText(\"v_role\", d.role || \"\\u2014\");\n"
    "  setText(\"v_clockid\", d.clock_id || \"\\u2014\");\n"
    "  setText(\"v_utc\", d.utc_time || \"--:--:--\");\n"
    "  setText(\"v_tai\", \"+\" + (d.tai_offset != null ? d.tai_offset : \"?\") + \" s\");\n"
    "  setText(\"v_sync_int\", (d.sync_interval_ms || 1000) + \" ms\");\n"
    "  setText(\"v_ann_int\",  (d.announce_interval_ms || 2000) + \" ms\");\n"
    "  setText(\"v_seq\", (d.sync_seq != null ? d.sync_seq.toLocaleString() : \"?\") + \" \\u00B7 \" +\n"
    "                   (d.announce_seq != null ? d.announce_seq.toLocaleString() : \"?\"));\n"
    "  setText(\"v_path\", d.path_delay_ns != null ? (d.path_delay_ns + \" ns\") : \"\\u2014 (master)\");\n"
    "  setText(\"v_slaves\", (d.slaves_active != null ? d.slaves_active : \"?\") + \" / \" +\n"
    "                      (d.slaves_max || 8));\n"
    "\n"
    "  /* Servo */\n"
    "  setText(\"v_servo\", stateUp);\n"
    "  const sv = $(\"v_servo\");\n"
    "  sv.className = \"value \" + (stateUp === \"LOCKED\" ? \"ok\" :\n"
    "                              stateUp === \"HOLDOVER\" ? \"warn\" :\n"
    "                              stateUp === \"FAULT\" || stateUp === \"NO_LINK\" ? \"err\" : \"\");\n"
    "  setText(\"v_integ\", d.integrator != null ? d.integrator.toFixed(2) : \"\\u2014\");\n"
    "  setText(\"v_lockq\", (d.lock_qual != null ? d.lock_qual : \"?\") + \" / \" +\n"
    "                     (d.lock_qual_window || 64));\n"
    "  setText(\"v_pps\", d.pps_count != null ? d.pps_count.toLocaleString() : \"\\u2014\");\n"
    "  /* Sample rejects: lifetime total, with a live \"REJ n/45\" warning while a\n"
    "   * reject streak is climbing (mirrors the OLED screen-2 indicator). Green at\n"
    "   * 0, info-blue once any have occurred (self-healed), warn/err as a streak\n"
    "   * approaches the re-acquire threshold. */\n"
    "  const rv = $(\"v_reject\");\n"
    "  if (rv) {\n"
    "    const total = (d.reject_total != null) ? d.reject_total : null;\n"
    "    const streak = (d.reject_streak != null) ? d.reject_streak : 0;\n"
    "    const reacq = d.reject_reacquire_at || 45;\n"
    "    if (total == null) {\n"
    "      setText(\"v_reject\", \"\\u2014\");\n"
    "      rv.className = \"value dim\";\n"
    "    } else if (streak > 0) {\n"
    "      setText(\"v_reject\", \"REJ \" + streak + \"/\" + reacq + \"  (\" + total.toLocaleString() + \" total)\");\n"
    "      rv.className = \"value \" + (streak >= reacq * 0.5 ? \"err\" : \"warn\");\n"
    "    } else {\n"
    "      setText(\"v_reject\", total.toLocaleString() + (total === 0 ? \" (none)\" : \" total\"));\n"
    "      rv.className = \"value \" + (total === 0 ? \"ok\" : \"info\");\n"
    "    }\n"
    "  }\n"
    "  setText(\"v_phc\", d.phc_residual_ns != null ? ((d.phc_residual_ns >= 0 ? \"+\" : \"\") + d.phc_residual_ns + \" ns\") : \"\\u2014\");\n"
    "  setText(\"v_holdto\", (d.holdover_timeout_s || 5) + \" s\");\n"
    "  const stl = $(\"v_settled\");\n"
    "  setText(\"v_settled\", d.settled ? \"yes\" : \"no\");\n"
    "  stl.className = \"value \" + (d.settled ? \"ok\" : \"warn\");\n"
    "  setText(\"v_gnssage\", d.gnss_age_s != null ? (d.gnss_age_s + \" s ago\") : \"\\u2014\");\n"
    "  setText(\"v_ppsled\", d.pps_led_active ? \"blinking\" : \"idle\");\n"
    "\n"
    "  /* Tasks */\n"
    "  if (Array.isArray(d.tasks)) {\n"
    "    const body = $(\"tasksBody\");\n"
    "    setText(\"b_tasks\", d.tasks.length + \" active \\u00B7 multicore\");\n"
    "    body.innerHTML = d.tasks.map(t => {\n"
    "      const meta = TASK_META[t.name] || { icon: \"\\u{1F539}\", role: \"\\u2014\" };\n"
    "      const used = (t.stack_bytes && t.hwm_bytes != null)\n"
    "                 ? Math.round(100 * (1 - t.hwm_bytes / t.stack_bytes))\n"
    "                 : 0;\n"
    "      const usedBytes = (t.stack_bytes != null && t.hwm_bytes != null)\n"
    "                      ? (t.stack_bytes - t.hwm_bytes)\n"
    "                      : 0;\n"
    "      const usedDisp = usedBytes >= 1024\n"
    "                     ? (usedBytes/1024).toFixed(1) + \" KB\"\n"
    "                     : usedBytes + \" B\";\n"
    "      return \"\"\n"
    "        + \"<tr>\"\n"
    "        + '<td><span class=\"tname\"><span class=\"icon\">' + meta.icon + \"</span>\" + t.name + \"</span></td>\"\n"
    "        + '<td><span class=\"' + prioClass(t.priority) + '\">' + t.priority + \"</span></td>\"\n"
    "        + \"<td>\" + (t.stack_bytes != null ? t.stack_bytes + \" B\" : \"\\u2014\") + \"</td>\"\n"
    "        + '<td><span class=\"bar\"><i style=\"width:' + used + '%\"></i></span>' + usedDisp + \"</td>\"\n"
    "        + \"<td>\" + (t.core != null ? t.core : \"\\u2014\") + \"</td>\"\n"
    "        + \"<td>\" + meta.role + \"</td>\"\n"
    "        + \"</tr>\";\n"
    "    }).join(\"\");\n"
    "  }\n"
    "\n"
    "  /* Footer timestamp */\n"
    "  const now = new Date();\n"
    "  const pad = (n) => String(n).padStart(2, \"0\");\n"
    "  setText(\"lastRefresh\", pad(now.getUTCHours()) + \":\" + pad(now.getUTCMinutes()) + \":\" + pad(now.getUTCSeconds()) + \" UTC\");\n"
    "}\n"
    "\n"
    "/* ─── Load / Soak monitor (opt-in; polls /api/health only when started) ─── */\n"
    "const HCAP = 180;\n"
    "const HJIT = [], HHEAP = [];\n"
    "let monTimer = null;\n"
    "\n"
    "function fmtBytes(b){ if (b==null) return \"\\u2014\"; if (b>=1048576) return (b/1048576).toFixed(2)+\" MB\"; if (b>=1024) return (b/1024).toFixed(1)+\" KB\"; return b+\" B\"; }\n"
    "\n"
    "function drawSpark(id, arr, color){\n"
    "  const c = $(id); if (!c) return; const ctx = c.getContext(\"2d\");\n"
    "  const W = c.width, H = c.height; ctx.clearRect(0,0,W,H);\n"
    "  if (arr.length < 2) return;\n"
    "  let mn = Math.min.apply(null, arr), mx = Math.max.apply(null, arr);\n"
    "  if (mx - mn < 1e-9) { mn -= 1; mx += 1; }\n"
    "  const n = arr.length, dx = W/(HCAP-1);\n"
    "  ctx.lineWidth = 1.5; ctx.strokeStyle = color; ctx.beginPath();\n"
    "  for (let i=0;i<n;i++){ const x=i*dx; const y=H-3-((arr[i]-mn)/(mx-mn))*(H-6); if(i===0)ctx.moveTo(x,y); else ctx.lineTo(x,y); }\n"
    "  ctx.stroke();\n"
    "  ctx.globalAlpha=0.12; ctx.lineTo((n-1)*dx,H); ctx.lineTo(0,H); ctx.closePath(); ctx.fillStyle=color; ctx.fill(); ctx.globalAlpha=1;\n"
    "}\n"
    "\n"
    "function renderHealth(d){\n"
    "  const sj = d.sync_jitter || {};\n"
    "  const p2p = (sj.p2p_us!=null) ? sj.p2p_us : null;\n"
    "  setText(\"h_jit\", p2p!=null ? (p2p/1000).toFixed(2)+\" ms\" : \"\\u2014\");\n"
    "  setText(\"h_jit_sub\", \"win \" + (sj.window!=null?sj.window:0) + \" \\u00B7 mean \" + (sj.mean_us!=null?(sj.mean_us/1000).toFixed(3)+\" ms\":\"\\u2014\"));\n"
    "  const rx = d.rx_task || {};\n"
    "  setText(\"h_rxcpu\", rx.cpu_pct!=null ? rx.cpu_pct.toFixed(1)+\" %\" : (d.runtime_stats?\"0.0 %\":\"n/a\"));\n"
    "  setText(\"h_rxcpu_sub\", d.runtime_stats ? \"ptp_rx share of total\" : \"enable run-time stats\");\n"
    "  setText(\"h_heapmin\", d.heap ? fmtBytes(d.heap.min) : \"\\u2014\");\n"
    "  setText(\"h_heapmin_sub\", d.heap ? \"free now \" + fmtBytes(d.heap.free) : \"\\u2014\");\n"
    "  setText(\"h_rxstack\", rx.stack_hwm!=null ? fmtBytes(rx.stack_hwm) : \"\\u2014\");\n"
    "  setText(\"h_rxstack_sub\", rx.stack_size!=null ? \"of \" + fmtBytes(rx.stack_size) : \"headroom\");\n"
    "\n"
    "  if (p2p!=null){ HJIT.push(p2p); if(HJIT.length>HCAP)HJIT.shift(); }\n"
    "  if (d.heap && d.heap.min!=null){ HHEAP.push(d.heap.min/1024); if(HHEAP.length>HCAP)HHEAP.shift(); }\n"
    "  drawSpark(\"sp_jit\", HJIT, \"#ffb86c\"); drawSpark(\"sp_heap\", HHEAP, \"#50fa7b\");\n"
    "  setText(\"sp_jit_v\", p2p!=null ? p2p + \" \\u00B5s\" : \"\\u2014\");\n"
    "  setText(\"sp_heap_v\", (d.heap&&d.heap.min!=null) ? (d.heap.min/1024).toFixed(0)+\" KB\" : \"\\u2014\");\n"
    "\n"
    "  if (Array.isArray(d.tasks)){\n"
    "    const body = $(\"monTasksBody\");\n"
    "    body.innerHTML = d.tasks.slice().sort((a,b)=>(b.cpu_pct||0)-(a.cpu_pct||0)).map(t => {\n"
    "      const meta = TASK_META[t.name] || { icon:\"\\u{1F539}\" };\n"
    "      const cpu = (t.cpu_pct!=null) ? t.cpu_pct.toFixed(1)+\" %\" : \"\\u2014\";\n"
    "      const cpuW = (t.cpu_pct!=null) ? Math.max(0,Math.min(100,t.cpu_pct)) : 0;\n"
    "      const hwm = (t.stack_hwm!=null) ? fmtBytes(t.stack_hwm) : \"\\u2014\";\n"
    "      return \"<tr>\"\n"
    "        + '<td><span class=\"tname\"><span class=\"icon\">' + meta.icon + \"</span>\" + t.name + \"</span></td>\"\n"
    "        + '<td><span class=\"' + prioClass(t.prio) + '\">' + (t.prio!=null?t.prio:\"\\u2014\") + \"</span></td>\"\n"
    "        + '<td><span class=\"bar\"><i style=\"width:' + cpuW + '%\"></i></span>' + cpu + \"</td>\"\n"
    "        + \"<td>\" + hwm + \"</td>\"\n"
    "        + \"</tr>\";\n"
    "    }).join(\"\");\n"
    "  }\n"
    "\n"
    "  const now = new Date(); const pad = (n)=>String(n).padStart(2,\"0\");\n"
    "  setText(\"monLast\", pad(now.getUTCHours())+\":\"+pad(now.getUTCMinutes())+\":\"+pad(now.getUTCSeconds())+\" UTC\");\n"
    "  setText(\"monRt\", d.runtime_stats ? \"run-time stats: on\" : \"run-time stats: OFF (cpu n/a)\");\n"
    "}\n"
    "\n"
    "async function healthPoll(){\n"
    "  try {\n"
    "    const r = await fetch(\"/api/health\", { cache:\"no-store\" });\n"
    "    if (!r.ok) throw new Error(\"HTTP \"+r.status);\n"
    "    renderHealth(await r.json());\n"
    "  } catch (err) {\n"
    "    setText(\"monRt\", \"poll failed: \" + err.message);\n"
    "    console.warn(\"health poll failed:\", err);\n"
    "  }\n"
    "}\n"
    "\n"
    "function setMonitoring(on){\n"
    "  const btn = $(\"monToggle\"), txt = $(\"monToggleText\"), badge = $(\"monBadge\");\n"
    "  if (on){\n"
    "    $(\"monIdle\").style.display = \"none\"; $(\"monBody\").style.display = \"block\";\n"
    "    btn.classList.add(\"on\"); txt.textContent = \"Stop monitoring\";\n"
    "    badge.textContent = \"monitoring \\u00B7 \" + HEALTH_POLL_MS + \" ms\";\n"
    "    setText(\"monInt\", HEALTH_POLL_MS);\n"
    "    healthPoll();\n"
    "    monTimer = setInterval(healthPoll, HEALTH_POLL_MS);\n"
    "  } else {\n"
    "    if (monTimer){ clearInterval(monTimer); monTimer = null; }\n"
    "    btn.classList.remove(\"on\"); txt.textContent = \"Start monitoring\";\n"
    "    badge.textContent = \"stopped \\u00B7 polls /api/health\";\n"
    "    poll();\n"
    "  }\n"
    "}\n"
    "\n"
    "$(\"monToggle\").addEventListener(\"click\", () => setMonitoring(monTimer === null));\n"
    "$(\"monIdleMs\").textContent = HEALTH_POLL_MS;\n"
    "\n"
    "/* ─── Polling ─── */\n"
    "async function poll() {\n"
    "  /* Opt-in: while monitoring is active and the box is checked, skip the\n"
    "     /api/status request entirely so the page issues only /api/health. */\n"
    "  const cb = $(\"monPauseStatus\");\n"
    "  if (monTimer !== null && cb && cb.checked) {\n"
    "    const pill = $(\"hdrStatus\");\n"
    "    if (pill) pill.className = \"status-pill warn\";\n"
    "    setText(\"hdrStatusText\", \"STATUS POLL PAUSED\");\n"
    "    return;\n"
    "  }\n"
    "  try {\n"
    "    const r = await fetch(\"/api/status\", { cache: \"no-store\" });\n"
    "    if (!r.ok) throw new Error(\"HTTP \" + r.status);\n"
    "    const d = await r.json();\n"
    "    render(d);\n"
    "  } catch (err) {\n"
    "    const pill = $(\"hdrStatus\");\n"
    "    pill.className = \"status-pill err\";\n"
    "    setText(\"hdrStatusText\", \"CONN LOST\");\n"
    "    console.warn(\"poll failed:\", err);\n"
    "  }\n"
    "}\n"
    "\n"
    "poll();\n"
    "setInterval(poll, 5000);\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";

#undef SP_STR
#undef SP_STR2

#ifdef __cplusplus
}
#endif

/* ----------------------------------------------------------------------------
 * JSON CONTRACT for GET /api/status
 *
 * The page expects this JSON shape. Any field may be omitted; the UI shows
 * an em-dash for missing values. All numbers are plain JSON numbers (not
 * strings).
 *
 * {
 *   "chip":              "ESP32-P4",
 *   "chip_rev":          "v1.0",
 *   "cpu_mhz":           360,
 *   "project":           "PTP_Master",
 *   "app_version":       "819246f-dirty",
 *   "idf_version":       "v5.5.4",
 *   "compile_time":      "May 12 2026 16:24",
 *   "elf_sha":           "d25969555aabbccdd...",
 *   "flash_mb":          16,
 *   "flash_mode":        "DIO",
 *   "flash_mhz":         80,
 *   "uptime_s":          10053,
 *
 *   "heap_free":         428032,   // bytes -- heap_caps_get_free_size(MALLOC_CAP_INTERNAL)
 *   "heap_min":          398336,   // bytes -- heap_caps_get_minimum_free_size(MALLOC_CAP_INTERNAL)
 *   "heap_lfb":          262144,   // bytes -- heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL)
 *   "heap_leak":         0,        // bytes delta vs. boot baseline
 *   "retent_total":     172032,   // bytes with MALLOC_CAP_RETENTION
 *   "retent_free":      145120,   // currently free bytes in that capability heap
 *   "ram1_kb":           384,
 *   "ram2_kb":           18,
 *   "rtc_kb":            31,
 *   "tcm_kb":            7,
 *
 *   "link_up":           true,
 *   "l2tap_ready":       true,
 *   "ip":                "192.168.5.142",
 *   "ip_source":         "DHCP lease",
 *   "mac":               "30:ED:A0:E2:33:D3",
 *   "hostname":          "radiant-captain-james-smith",
 *   "emac_restarts":     0,        // g_emac_restart_count
 *   "promiscuous":       false,
 *   "wdt_healthy":       true,
 *
 *   "role":              "MASTER",      // or "SLAVE"
 *   "clock_id":          "30ED A0FF FEE2 33D3",
 *   "utc_time":          "14:38:21",
 *   "tai_offset":        37,            // g_utc_offset
 *   "sync_interval_ms":  1000,
 *   "announce_interval_ms": 2000,
 *   "sync_seq":          10031,         // g_sync_seq
 *   "announce_seq":      5015,          // g_announce_seq
 *   "path_delay_ns":     null,          // master => null; slave => g_slave_path_delay_ns
 *   "slaves_active":     3,             // slave_active_count()
 *   "slaves_max":        8,             // SLAVE_TRACK_MAX
 *
 *   "servo_state":       "LOCKED",      // NO_LINK | ACQUIRING | LOCKED | HOLDOVER | FAULT
 *   "locked_for":        "00:42:17",
 *   "offset_ns":         128,           // g_last_offset
 *   "freq_ppb":          -12.4,         // g_freq_ppb
 *   "integrator":        -3.21,         // g_integral
 *   "lock_qual":         61,            // g_lock_qual_count
 *   "lock_qual_window":  64,            // LOCK_QUAL_WINDOW
 *   "pps_count":         2548,          // g_pps_capture_seq
 *   "reject_total":      0,             // g_total_rejects (lifetime, since boot)
 *   "reject_streak":     0,             // g_consecutive_rejects (live run)
 *   "reject_reacquire_at":45,           // REJECT_STREAK_REACQUIRE
 *   "phc_residual_ns":   42,            // g_phc_offset_ns
 *   "holdover_timeout_s":5,             // HOLDOVER_TIMEOUT_SEC
 *   "settled":           true,          // g_settled_after_holdover
 *   "gnss_age_s":         2,
 *   "gnss_fix":           true,
 *   "pps_led_active":    true,
 *
 *   "tasks": [
 *     { "name": "ptp_rx",   "priority": 7, "stack_bytes": 8192, "hwm_bytes": 4734, "core": 0 },
 *     { "name": "ptp_tx",   "priority": 5, "stack_bytes": 8192, "hwm_bytes": 5298, "core": 0 },
 *     { "name": "gnss",      "priority": 5, "stack_bytes": 6144, "hwm_bytes": 2752, "core": 1 },
 *     { "name": "servo",    "priority": 6, "stack_bytes": 6144, "hwm_bytes": 3211, "core": 1 },
 *     { "name": "pps_task", "priority": 7, "stack_bytes": 4096, "hwm_bytes": 2868, "core": 1 },
 *     { "name": "pps_led",  "priority": 1, "stack_bytes": 2048, "hwm_bytes": 1600, "core": 0 },
 *     { "name": "led",      "priority": 1, "stack_bytes": 2048, "hwm_bytes": 1644, "core": 0 },
 *     { "name": "display",  "priority": 1, "stack_bytes": 4096, "hwm_bytes": 2560, "core": 0 },
 *     { "name": "btn",      "priority": 1, "stack_bytes": 2048, "hwm_bytes": 1680, "core": 0 },
 *     { "name": "dhcp_fb",  "priority": 2, "stack_bytes": 3072, "hwm_bytes": 2304, "core": 0 },
 *     { "name": "heap_mon", "priority": 1, "stack_bytes": 3072, "hwm_bytes": 2334, "core": 0 },
 *     { "name": "wdt",      "priority": 1, "stack_bytes": 4096, "hwm_bytes": 2950, "core": 0 },
 *     { "name": "main",     "priority": 1, "stack_bytes": 4096, "hwm_bytes": 2900, "core": 0 }
 *   ]
 * }
 *
 * Use uxTaskGetSystemState() to populate the "tasks" array. hwm_bytes is
 * the FreeRTOS high-water-mark (uxTaskGetStackHighWaterMark) multiplied by
 * sizeof(StackType_t) -- i.e. the smallest amount of free stack ever seen.
 * --------------------------------------------------------------------------- */

#endif /* STATUS_PAGE_H */
